/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Statistics from calculating a workbook. */
export declare class CalculationStats {
  /** Number of formulas found */
  get formulaCount(): number
  /** Number of cells calculated */
  get cellsCalculated(): number
  /** Number of errors encountered */
  get errors(): number
  /** Number of circular references detected */
  get circularReferences(): number
  /** Number of volatile cells (e.g., NOW(), RAND()) */
  get volatileCells(): number
  /** Whether iterative calculation converged */
  get converged(): boolean
  /** Number of iterations performed */
  get iterations(): number
}

/**
 * Represents a cell value in a spreadsheet.
 *
 * Cell values can be one of several types:
 * - Empty (null/undefined)
 * - Number
 * - Text (string)
 * - Boolean
 * - Error (like "#DIV/0!")
 * - Formula cached results are exposed as regular cell values; formula text lives on Worksheet accessors
 */
export declare class CellValue {
  /** Check if the cell is empty */
  get isEmpty(): boolean
  /** Check if the cell contains a number */
  get isNumber(): boolean
  /** Check if the cell contains text */
  get isText(): boolean
  /** Check if the cell contains a boolean */
  get isBoolean(): boolean
  /** Check if the cell contains an error */
  get isError(): boolean
  /** Get the value as a number, or null if not a number */
  asNumber(): number | null
  /** Get the value as text, or null if not text */
  asText(): string | null
  /** Get the value as a boolean, or null if not a boolean */
  asBoolean(): boolean | null
  /** Get the error string, or null if not an error */
  asError(): string | null
  /** Convert to a JavaScript native value (number, string, boolean, or null) */
  toJs(): number | string | boolean | null
  /** Get string representation of the cell value */
  toString(): string
}

/**
 * A workbook containing one or more worksheets.
 *
 * This is the main entry point for working with spreadsheet files.
 *
 * @example
 * ```typescript
 * const wb = new Workbook();
 * const sheet = wb.getSheet(0);
 * sheet.setCell("A1", 10);
 * sheet.setCell("A2", 20);
 * sheet.setFormula("A3", "=A1+A2");
 * wb.calculate();
 * console.log(sheet.getCalculatedValue("A3").asNumber()); // 30
 * ```
 */
export declare class Workbook {
  /** Synchronize current form-control state into linked cells. */
  syncFormControls(): number
  /** Drive form controls from formula-backed linked cells. */
  syncFormControlsFromLinkedCells(): number
  /** Whether the workbook has no worksheets. */
  get isEmpty(): boolean
  /** The index of the active (selected) worksheet. */
  get activeSheet(): number
  /** Get the index of a worksheet by name, or null if not found. */
  sheetIndex(name: string): number | null
  /** Workbook-level settings (date system, protection, etc.). */
  get settings(): JsWorkbookSettings
  /** Workbook structure/window protection settings, or null if unprotected. */
  get workbookProtection(): JsWorkbookProtection | null
  /** Get all named ranges defined in the workbook. */
  get namedRanges(): Array<JsNamedRange>
  /**
   * The workbook theme's 12 clrScheme colors as `RRGGBB` hex, in
   * theme-index order (background 1, text 1, background 2, text 2,
   * accent 1-6, hyperlink, followed hyperlink). The Office default
   * palette when the file carries no theme.
   */
  get themePalette(): Array<string>
  /**
   * Resolve a drawing color to display RGB (`RRGGBB` hex) against
   * this workbook's theme palette. `auto` has no fixed RGB and
   * resolves to `null`.
   */
  resolveColor(color: object): string | null
  /** Get all chart sheets. */
  get chartsheets(): Array<JsChartSheet>
  /** Get the number of chart sheets. */
  get chartsheetCount(): number
  /** Get the tab-bar ordering of worksheets and chartsheets. */
  get sheetOrder(): Array<JsSheetSlot>
  /** Total number of tabs (worksheets + chartsheets). */
  get totalSheetCount(): number
  /** Create a new empty workbook with one worksheet */
  constructor()
  /**
   * Open a workbook from a file
   *
   * Supported formats:
   * - `.xlsx` (Excel 2007+)
   * - `.xls` (Legacy Excel)
   * - `.csv` (Comma-separated values)
   *
   * @param path - Path to the file
   */
  static open(path: string): Workbook
  /**
   * Load a workbook from bytes (Buffer/Uint8Array), auto-detecting the format.
   *
   * Supports XLSX and XLS formats. The format is detected from magic bytes.
   *
   * @param data - The file content as a Buffer
   */
  static fromBytes(data: Buffer): Workbook
  /**
   * Load a workbook from a CSV string
   *
   * @param csv - The CSV content as a string
   */
  static fromCsvString(csv: string): Workbook
  /**
   * Save the workbook to a file.
   *
   * Form-control state is synchronized into linked cells in the output,
   * replacing existing values and formulas there; this workbook is left
   * unchanged.
   *
   * The format is determined by the file extension:
   * - `.xlsx` for Excel format
   * - `.xls` for legacy Excel binary format
   * - `.csv` for CSV format (first sheet only)
   *
   * @param path - Path to save to
   */
  save(path: string): void
  /**
   * Save the workbook to a password-protected file. Form-control state is
   * synchronized into linked cells in the serialized file, replacing
   * existing values and formulas there. The encryption
   * variant is selected via `profile`:
   *
   * - `"default"` (or null) - Agile-256 for .xlsx, RC4 CryptoAPI 128 for .xls
   * - `"agile"` - OOXML Agile (AES-CBC + HMAC-SHA*); pass keyBits to override
   * - `"standard"` - OOXML Standard Encryption (AES-ECB)
   * - `"rc4-cryptoapi"` - XLS RC4 CryptoAPI; keyBits 40 or 128
   * - `"rc4-legacy"` - XLS legacy RC4 (MD5 KDF)
   * - `"xor"` - XLS XOR Obfuscation; round-trips via duke-sheets but
   *   does not interoperate with modern Excel
   *
   * @param path - Path to save to
   * @param password - Password to encrypt with
   * @param profile - Optional encryption variant (see above)
   * @param keyBits - Optional key size override (Agile / RC4 CryptoAPI)
   * @param spinCount - Optional iteration count (Agile only; default 100,000)
   */
  saveWithPassword(path: string, password: string, profile?: string | undefined | null, keyBits?: number | undefined | null, spinCount?: number | undefined | null): void
  /**
   * Open a password-protected workbook.
   *
   * @param path - File path
   * @param password - Password to attempt
   * @param skipIntegrityCheck - If true, skip the HMAC integrity
   *   check on Agile-encrypted files (matches Office behaviour).
   *   Default false.
   */
  static openWithPassword(path: string, password: string, skipIntegrityCheck?: boolean | undefined | null): Workbook
  /**
   * Save the workbook as a CSV string (first sheet only, with
   * form-control state synchronized into linked cells in the output)
   */
  saveCsvString(): string
  /** Get the number of worksheets */
  get sheetCount(): number
  /** Get a list of all worksheet names */
  get sheetNames(): Array<string>
  /**
   * Get a worksheet by index (number) or name (string)
   *
   * @param indexOrName - Either a zero-based index or a sheet name
   * @throws Error if index out of range or name not found
   */
  getSheet(indexOrName: number | string): Worksheet
  /**
   * Add a new worksheet with the given name
   *
   * @param name - Name for the new worksheet
   * @returns Index of the new worksheet
   */
  addSheet(name: string): number
  /** Set or clear workbook structure/window protection settings. */
  setWorkbookProtection(protection?: JsWorkbookProtectionInput | undefined | null): void
  /**
   * Remove a worksheet by index
   *
   * @param index - Zero-based index of the worksheet to remove
   */
  removeSheet(index: number): void
  /**
   * Calculate all formulas in the workbook.
   *
   * Optionally accepts calculation options. Callbacks (`webServiceFn`, `rtdFn`, `externalFn`)
   * are only supported on the async path via `calculateAsync`.
   *
   * @param options - Optional calculation options
   * @returns Statistics about the calculation
   */
  calculate(options?: JsCalculationOptions | undefined | null): CalculationStats
  /**
   * Define a named range
   *
   * @param name - Name for the range (e.g., "TaxRate")
   * @param refersTo - What the name refers to (e.g., "Sheet1!$A$1" or "0.05")
   */
  defineName(name: string, refersTo: string): void
  /**
   * Get a named range definition
   *
   * @param name - Name to look up
   * @returns The refers_to string, or null if not found
   */
  getNamedRange(name: string): string | null
  /**
   * Save the workbook to a file asynchronously (non-blocking).
   * Form-control state is synchronized into linked cells in the output
   * without changing this workbook.
   *
   * @param path - Path to save to
   * @returns Promise<void>
   */
  saveAsync(path: string): Promise<void>
  /**
   * Calculate all formulas asynchronously (non-blocking).
   *
   * Optionally accepts calculation options with callback functions:
   * - `webServiceFn`: called for each `WEBSERVICE(url)` evaluation
   * - `rtdFn`: called for each `RTD(progId, server, ...topics)` evaluation
   *
   * Callbacks must return a Promise. Use `async (url) => ...` or
   * wrap synchronous results: `async (url) => mySyncFn(url)`.
   *
   * @param options - Optional calculation options with optional callbacks
   * @returns Promise<CalculationStats>
   */
  calculateAsync(options?: JsCalculationOptions & { webServiceFn?: (url: string) => Promise<string | null | undefined>; rtdFn?: (progId: string, server: string, topics: string[]) => Promise<string | null | undefined>; externalFn?: (book: string, name: string, args: string[]) => Promise<string | null | undefined>; externalFnFn?: (book: string, name: string, args: string[]) => Promise<string | null | undefined> }): Promise<CalculationStats>
}

/**
 * A worksheet within a workbook.
 *
 * Worksheets contain cells organized in rows and columns. Each cell can
 * contain a value (number, text, boolean) or a formula.
 */
export declare class Worksheet {
  /** Recursive top-level drawings in back-to-front z-order. */
  get drawings(): object[]
  /** All form controls in depth-first drawing order. */
  get formControls(): object[]
  get formControlCount(): number
  /** All embedded images in depth-first drawing order, without image bytes. */
  get images(): object[]
  get imageCount(): number
  /** All standard charts in depth-first drawing order. */
  get charts(): object[]
  get chartCount(): number
  /** All ChartEx charts in depth-first drawing order. */
  get chartsEx(): object[]
  get chartExCount(): number
  /** Append a top-level drawing and return its global z-order index. */
  addDrawing(input: object): number
  /**
   * Insert a top-level drawing at a global z-order index. Drawing
   * paths are positional; mutating the list invalidates previously
   * returned paths.
   */
  insertDrawing(index: number, input: object): void
  /**
   * Replace a top-level drawing or nested group child. Drawing
   * paths are positional; mutating the list invalidates previously
   * returned paths.
   */
  setDrawing(path: number[], input: object): void
  /**
   * Remove a top-level drawing or nested group child. Drawing
   * paths are positional; mutating the list invalidates previously
   * returned paths.
   */
  removeDrawing(path: Array<number>): void
  /**
   * Move a top-level drawing to another z-order index. Drawing
   * paths are positional; mutating the list invalidates previously
   * returned paths.
   */
  moveDrawing(from: number, to: number): void
  /**
   * Lazily copy the bytes for an image at a drawing path. Paths are
   * positional; mutating the drawing list invalidates previously
   * returned paths.
   */
  drawingImageData(path: Array<number>): Buffer
  /**
   * Lazily copy an image's SVG companion bytes, when present. Paths
   * are positional; mutating the drawing list invalidates previously
   * returned paths.
   */
  drawingSvgData(path: Array<number>): Buffer | null
  /** Apply checkbox/radio semantics and synchronize linked cells immediately. */
  setFormControlCheckState(path: Array<number>, state: JsCheckState): JsFormControlInteractionResult
  /** Sheet visibility: "visible", "hidden", or "veryHidden". */
  get visibility(): string
  /** Whether the worksheet is selected. */
  get isSelected(): boolean
  /** Zoom scale percentage, or null if default. */
  get zoomScale(): number | null
  /** Sheet tab color, or null if default. */
  get tabColor(): JsColor | null
  /** Whether the worksheet has no cells. */
  get isEmpty(): boolean
  /** Total number of cells with data. */
  get cellCount(): number
  /** Sheet view selections. */
  get selections(): Array<JsSelection>
  /** Get the resolved style for a cell by address (e.g., "A1"). */
  getCellStyle(address: string): JsStyle | null
  /** Get the resolved style for a cell by row/col (0-based). */
  getCellStyleAt(row: number, col: number): JsStyle | null
  /** Get the display-formatted value of a cell (e.g., "$1,234.56"). */
  getFormattedValue(address: string): string
  /** Get the display-formatted value by row/col (0-based). */
  getFormattedValueAt(row: number, col: number): string
  /**
   * Get a batch of sparse rows starting from `start_row`.
   *
   * Returns up to `max_rows` rows that contain data or metadata.
   * Each row contains only relevant cells (sparse representation).
   * Returns an empty array when no more rows exist.
   *
   * When metadata flags are enabled (includeStyles, includeMergeInfo, etc.),
   * cells with that metadata are included even if their value is empty.
   */
  getRowsBatch(startRow: number, maxRows: number, options?: JsRowsOptions | undefined | null): Array<JsRow>
  /** Default row height in points. */
  get defaultRowHeight(): number
  /** Default column width in character units. */
  get defaultColumnWidth(): number
  /** Whether a row is hidden. */
  isRowHidden(row: number): boolean
  /** Whether a column is hidden. */
  isColumnHidden(col: number): boolean
  /** Get the outline (grouping) level of a row. */
  getRowOutlineLevel(row: number): number
  /** Get the outline (grouping) level of a column. */
  getColumnOutlineLevel(col: number): number
  /** Whether a row group is collapsed. */
  isRowCollapsed(row: number): boolean
  /** Whether a column group is collapsed. */
  isColumnCollapsed(col: number): boolean
  /** Freeze pane settings, or null if no freeze panes. */
  get freezePanes(): JsFreezePanes | null
  /** Split pane settings, or null if no split panes. */
  get splitPanes(): JsSplitPanes | null
  /** Get the hyperlink on a cell, or null if none. */
  getHyperlink(address: string): JsHyperlink | null
  /** Get the hyperlink on a cell by row/col (0-based), or null if none. */
  getHyperlinkAt(row: number, col: number): JsHyperlink | null
  /** Number of hyperlinks in the worksheet. */
  get hyperlinkCount(): number
  /** Get all hyperlinks as an array of `{ address, hyperlink }`. */
  get hyperlinks(): Array<JsHyperlinkEntry>
  /** Get the comment on a cell by address, or null if none. */
  getComment(address: string): JsComment | null
  /** Get the comment on a cell by row/col (0-based), or null if none. */
  getCommentAt(row: number, col: number): JsComment | null
  /** Whether a cell has a comment (by address). */
  hasComment(address: string): boolean
  /** Whether a cell has a comment (by row/col). */
  hasCommentAt(row: number, col: number): boolean
  /** Number of comments in the worksheet. */
  get commentCount(): number
  /** Get all comments as an array of `{ row, col, comment }`. */
  get comments(): Array<JsCommentEntry>
  /** List of distinct comment authors. */
  get commentAuthors(): Array<string>
  /** Get all tables in the worksheet. */
  get tables(): Array<JsTable>
  /** Get a table by name, or null if not found. */
  getTableByName(name: string): JsTable | null
  /** Number of tables in the worksheet. */
  get tableCount(): number
  /** Get all data validation rules. */
  get dataValidations(): Array<JsDataValidation>
  /** Number of data validation rules. */
  get dataValidationCount(): number
  /** Get all conditional formatting rules. */
  get conditionalFormats(): Array<JsConditionalFormatRule>
  /** Number of conditional formatting rules. */
  get conditionalFormatCount(): number
  /** The auto-filter on this worksheet, or null if none. */
  get autoFilter(): JsAutoFilter | null
  /** Sheet protection settings, or null if unprotected. */
  get protection(): JsSheetProtection | null
  /** Protected editable ranges on this worksheet. */
  get protectedRanges(): Array<JsProtectedRange>
  /** Page setup / print settings. */
  get pageSetup(): JsPageSetup
  /** Print area range string, or null if not set. */
  get printArea(): string | null
  /** Repeat rows at top of each printed page as `[startRow, endRow]`, or null. */
  get repeatRows(): Array<number> | null
  /** Repeat columns at left of each printed page as `[startCol, endCol]`, or null. */
  get repeatCols(): Array<number> | null
  /** Manual row page breaks. */
  get rowBreaks(): Array<JsPageBreak>
  /** Manual column page breaks. */
  get colBreaks(): Array<JsPageBreak>
  /** Get the formula text of a cell by row/col (0-based), or null if not a formula cell. */
  getFormulaAt(row: number, col: number): string | null
  /** Get the number of formula cells in this worksheet. */
  get formulaCount(): number
  /** Get all formula cells as an array of `{ row, col, formula }`. */
  get formulaCells(): Array<JsFormulaCell>
  /** Whether a cell is a spill target (receives a spilled value from a dynamic array formula). */
  isSpillTarget(row: number, col: number): boolean
  /** Whether a cell is the source of a spill (has a dynamic array formula with results). */
  isSpillSource(row: number, col: number): boolean
  /** Get the source cell of a spill target, or null if not a spill target. */
  getSpillSource(row: number, col: number): JsSpillSource | null
  /** Whether the worksheet uses the 1904 date system. */
  get date1904(): boolean
  /** Get all merged regions as structured objects with start/end row/col. */
  get mergedRegions(): Array<JsMergedRegion>
  /**
   * Get the merge span for a cell if it is the top-left origin of a merged region.
   *
   * Returns `{ rowSpan, colSpan }` if the cell is a merge origin, or null otherwise.
   */
  getMergeSpan(row: number, col: number): JsMergeSpan | null
  /** Whether a cell is a non-origin member of a merged region (should be skipped when rendering). */
  isMergedSecondary(row: number, col: number): boolean
  /** Get the worksheet name */
  get name(): string
  /**
   * Set a cell value by address (e.g., "A1", "B2")
   *
   * The value can be:
   * - `null` or `undefined` (clears the cell)
   * - `number` (numeric value)
   * - `string` (text)
   * - `boolean`
   */
  setCell(address: string, value?: number | string | boolean | undefined | null): void
  /**
   * Set a formula in a cell
   *
   * @param address - Cell address (e.g., "A1")
   * @param formula - Formula string (e.g., "=SUM(A1:A10)")
   */
  setFormula(address: string, formula: string): void
  /**
   * Set or update a cell style by address.
   *
   * A full style object returned by `getCellStyle()` can be used to copy a
   * style. Partial objects update only the provided top-level components.
   */
  setCellStyle(address: string, style: JsStylePatch): void
  /** Set or update a cell style by row/col (0-based). */
  setCellStyleAt(row: number, col: number, style: JsStylePatch): void
  /** Set or update the style for all cells in a range (e.g. "A1:C3"). */
  setRangeStyle(rangeStr: string, style: JsStylePatch): void
  /** Set or clear sheet protection settings. */
  setProtection(protection?: JsSheetProtectionInput | undefined | null): void
  /** Replace the protected editable ranges for this sheet. */
  setProtectedRanges(ranges: Array<JsProtectedRangeInput>): void
  /** Get the raw cell value (not calculated) */
  getCell(address: string): CellValue
  /** Get the raw cell value by row/col (0-based). */
  getCellAt(row: number, col: number): CellValue
  /**
   * Get the calculated value of a cell
   *
   * For formulas, this returns the computed result.
   * For regular values, returns the value itself.
   */
  getCalculatedValue(address: string): CellValue
  /** Get the calculated value of a cell by row/col (0-based). */
  getCalculatedValueAt(row: number, col: number): CellValue
  /**
   * Get the used range as `{ minRow, minCol, maxRow, maxCol }` or null
   * if the worksheet is empty.
   */
  get usedRange(): UsedRange | null
  /** Get IMAGE() metadata for a cell, or null if no image. */
  getImageAt(row: number, col: number): JsImageInfo | null
  /** Set the height of a row in points */
  setRowHeight(row: number, height: number): void
  /** Set the width of a column in character units */
  setColumnWidth(col: number, width: number): void
  /** Get the row height in points, or null if not explicitly set */
  getRowHeight(row: number): number | null
  /** Get the column width in character units, or null if not explicitly set */
  getColumnWidth(col: number): number | null
  /** Merge cells in a range (e.g., "A1:C3") */
  mergeCells(rangeStr: string): void
  /** Unmerge cells in a range */
  unmergeCells(rangeStr: string): boolean
}

/**
 * Load a workbook from bytes asynchronously (non-blocking).
 *
 * Auto-detects format (XLSX or XLS) from magic bytes.
 *
 * @param data - The file content as a Buffer
 * @returns Promise<Workbook>
 */
export declare function fromBytesAsync(data: Buffer): Promise<Workbook>

/** Text alignment settings. */
export interface JsAlignment {
  horizontal: string
  vertical: string
  wrapText: boolean
  shrinkToFit: boolean
  indent: number
  /** Rotation in degrees (-90 to 90, or 255 for vertical text). */
  rotation: number
  readingOrder: string
}

/** Alignment input for style setters. */
export interface JsAlignmentPatch {
  horizontal?: string
  vertical?: string
  wrapText?: boolean
  shrinkToFit?: boolean
  indent?: number
  rotation?: number
  readingOrder?: string
}

/** A standalone auto-filter on a worksheet. */
export interface JsAutoFilter {
  /** Range string the filter covers (e.g., `"A1:D10"`). */
  range: string
  filterColumns: Array<JsFilterColumn>
}

/** A chart axis. */
export interface JsAxis {
  title?: string
  minimum?: number
  maximum?: number
  majorUnit?: number
  minorUnit?: number
  /**
   * One of: `"Bottom"`, `"Top"`, `"Left"`, `"Right"`.
   * `bottom`, `top`, `left` or `right`; unset when the source omitted
   * it and the writer will supply the conventional one.
   */
  position?: string
  numberFormat?: JsChartNumberFormat
  majorGridlines: boolean
  minorGridlines: boolean
  majorGridlinesShapeProperties?: JsChartShapeProperties
  minorGridlinesShapeProperties?: JsChartShapeProperties
  majorTickMark?: string
  minorTickMark?: string
  labelPosition?: string
  delete?: boolean
  crosses?: string
  crossBetween?: string
  shapeProperties?: JsChartShapeProperties
}

/** A single border edge (line style + color). */
export interface JsBorderEdge {
  /**
   * One of: `"none"`, `"thin"`, `"medium"`, `"thick"`, `"dashed"`, `"dotted"`,
   * `"double"`, `"hair"`, `"mediumDashed"`, `"dashDot"`, `"mediumDashDot"`,
   * `"dashDotDot"`, `"mediumDashDotDot"`, `"slantDashDot"`.
   */
  style: string
  color: JsColor
}

/** Border edge input for style setters. */
export interface JsBorderEdgePatch {
  style?: string
  color?: JsColorInput
}

/** Cell border style. */
export interface JsBorderStyle {
  left?: JsBorderEdge
  right?: JsBorderEdge
  top?: JsBorderEdge
  bottom?: JsBorderEdge
  diagonal?: JsBorderEdge
  /** One of: `"none"`, `"down"`, `"up"`, `"both"`. */
  diagonalDirection: string
}

/** Border input for style setters. */
export interface JsBorderStylePatch {
  left?: JsBorderEdgePatch
  right?: JsBorderEdgePatch
  top?: JsBorderEdgePatch
  bottom?: JsBorderEdgePatch
  diagonal?: JsBorderEdgePatch
  diagonalDirection?: string
}

/**
 * Options for workbook calculation.
 *
 * All fields are optional and default to sensible values.
 */
export interface JsCalculationOptions {
  /** Enable iterative calculation for circular references (default: false) */
  iterative?: boolean
  /** Maximum iterations for circular references (default: 100) */
  maxIterations?: number
  /** Maximum change threshold for convergence (default: 0.001) */
  maxChange?: number
  /** Force recalculation of all cells, even if not dirty (default: true) */
  forceFullCalculation?: boolean
  /** Include volatile functions in calculation (NOW, TODAY, RAND, etc.) (default: true) */
  calculateVolatile?: boolean
  /**
   * Only calculate these sheet indices (and their transitive cross-sheet dependencies).
   * If empty or omitted, calculate all sheets.
   */
  sheets?: Array<number>
  /**
   * Maximum number of threads for parallel evaluation.
   * - null/undefined: use all available cores
   * - 1: force serial evaluation
   * - n: use at most n threads
   */
  maxThreads?: number
}

/** Cell protection settings. */
export interface JsCellProtection {
  locked: boolean
  hidden: boolean
}

/** Cell protection input for style setters. */
export interface JsCellProtectionPatch {
  locked?: boolean
  hidden?: boolean
}

/** A chart embedded in a worksheet. */
export interface JsChart {
  /** Chart type string, e.g. `"ColumnClustered"`, `"Line"`, `"Pie"`. */
  chartType: string
  title?: string
  series: Array<JsDataSeries>
  categoryAxis?: JsAxis
  valueAxis?: JsAxis
  legend?: JsLegend
  dataLabels?: JsDataLabels
  view3D?: JsView3D
  dataTable?: JsChartDataTable
  displayBlanksAs?: string
  plotVisibleOnly?: boolean
  layout?: JsLayout
  shapeProperties?: JsChartShapeProperties
  is3D: boolean
  varyColors?: boolean
  gapWidth?: number
  overlap?: number
  firstSliceAngle?: number
  holeSize?: number
  bubbleScale?: number
  showNegativeBubbles?: boolean
  autoTitleDeleted?: boolean
  roundedCorners?: boolean
  showDlblsOverMax?: boolean
  wireframe?: boolean
  radarStyle?: string
  typeGroups: Array<JsChartTypeGroup>
  axes: Array<JsChartAxis>
  dropLines?: JsChartLines
  highLowLines?: JsChartLines
  seriesLines?: JsChartLines
  upDownBars?: JsUpDownBars
  style?: JsChartStyle
  colorStyle?: JsChartColorStyle
}

export interface JsChartAxis {
  id: number
  crossId: number
  axis: JsAxis
}

/**
 * A chart colour style part. `raw` is set instead when the part could
 * not be modelled.
 */
export interface JsChartColorStyle {
  /** `cycle`, `withinLinear`, ... */
  method?: string
  id?: number
  /** Each colour as the XML it was read as. */
  colors: Array<string>
  variations: Array<string>
  raw?: string
}

/** Data table displayed beneath the chart. */
export interface JsChartDataTable {
  showHorizontalBorder?: boolean
  showVerticalBorder?: boolean
  showOutline?: boolean
  showKeys?: boolean
}

export interface JsChartEx {
  layout: string
  version?: string
  featureList?: string
  fallbackImg?: string
  title?: JsChartExTitle
  data: Array<JsChartExData>
  plotArea: JsChartExPlotArea
  legend?: JsChartExLegend
  shapeProperties?: JsChartShapeProperties
  formatOverrides: Array<JsChartExFormatOverride>
  printSettings?: JsChartExPrintSettings
  externalDataRelId?: string
  externalDataAutoUpdate?: boolean
  style?: JsChartStyle
  colorStyle?: JsChartColorStyle
}

export interface JsChartExAxis {
  id: number
  hidden?: boolean
  scaling: JsChartExScaling
  title?: JsChartExAxisTitle
  units?: JsChartExAxisUnits
  majorGridlines?: JsChartExGridlines
  minorGridlines?: JsChartExGridlines
  majorTickMarks?: string
  minorTickMarks?: string
  tickLabels: boolean
  numberFormat?: JsChartNumberFormat
  shapeProperties?: JsChartShapeProperties
}

export interface JsChartExAxisTitle {
  text?: string
  shapeProperties?: JsChartShapeProperties
}

export interface JsChartExAxisUnits {
  unit?: string
}

export interface JsChartExBinning {
  intervalClosed?: string
  underflow?: string
  overflow?: string
  binSize?: number
  binCount?: number
}

export interface JsChartExColorPosition {
  positionType: string
  value?: number
}

export interface JsChartExData {
  id: number
  dimensions: Array<JsChartExDimension>
}

export interface JsChartExDataLabel {
  idx: number
  position?: string
  visibilitySeriesName?: boolean
  visibilityCategoryName?: boolean
  visibilityValue?: boolean
  numberFormat?: JsChartNumberFormat
  separator?: string
  shapeProperties?: JsChartShapeProperties
}

export interface JsChartExDataLabels {
  position?: string
  visibilitySeriesName?: boolean
  visibilityCategoryName?: boolean
  visibilityValue?: boolean
  numberFormat?: JsChartNumberFormat
  separator?: string
  shapeProperties?: JsChartShapeProperties
  overrides: Array<JsChartExDataLabel>
  hiddenLabels: Array<number>
}

export interface JsChartExDataPoint {
  idx: number
  shapeProperties?: JsChartShapeProperties
}

export interface JsChartExDimension {
  dimType: string
  formula?: string
  nfFormula?: string
}

export interface JsChartExFormatOverride {
  idx: number
  shapeProperties?: JsChartShapeProperties
}

export interface JsChartExGeography {
  projectionType?: string
  viewedRegionType?: string
  cultureLanguage?: string
  cultureRegion?: string
  attribution?: string
}

export interface JsChartExGridlines {
  shapeProperties?: JsChartShapeProperties
}

export interface JsChartExHeaderFooter {
  alignWithMargins?: boolean
  differentOddEven?: boolean
  differentFirst?: boolean
  oddHeader?: string
  oddFooter?: string
  evenHeader?: string
  evenFooter?: string
  firstHeader?: string
  firstFooter?: string
}

export interface JsChartExLayoutPr {
  parentLabelLayout?: string
  regionLabelLayout?: string
  visibility?: JsChartExSeriesVisibility
  aggregation: boolean
  binning?: JsChartExBinning
  geography?: JsChartExGeography
  statistics?: JsChartExStatistics
  subtotals?: Array<number>
}

export interface JsChartExLegend {
  position?: string
  align?: string
  overlay?: boolean
  offset?: JsChartExOffset
  shapeProperties?: JsChartShapeProperties
}

export interface JsChartExOffset {
  top?: number
  left?: number
}

export interface JsChartExPageMargins {
  left?: number
  right?: number
  top?: number
  bottom?: number
  header?: number
  footer?: number
}

export interface JsChartExPageSetup {
  paperSize?: number
  firstPageNumber?: number
  orientation?: string
  blackAndWhite?: boolean
  draft?: boolean
  useFirstPageNumber?: boolean
  horizontalDpi?: number
  verticalDpi?: number
  copies?: number
}

export interface JsChartExPlotArea {
  plotSurface?: JsChartShapeProperties
  series: Array<JsChartExSeries>
  axes: Array<JsChartExAxis>
  shapeProperties?: JsChartShapeProperties
}

export interface JsChartExPrintSettings {
  headerFooter?: JsChartExHeaderFooter
  pageMargins?: JsChartExPageMargins
  pageSetup?: JsChartExPageSetup
}

export interface JsChartExScaling {
  scalingType: string
  gapWidth?: number
  min?: number
  max?: number
  majorUnit?: number
  minorUnit?: number
}

export interface JsChartExSeries {
  layout: string
  dataId: number
  uniqueId?: string
  hidden?: boolean
  ownerIdx?: number
  formatIdx?: number
  text?: JsChartExText
  dataLabels?: JsChartExDataLabels
  dataPoints: Array<JsChartExDataPoint>
  layoutProperties?: JsChartExLayoutPr
  axisIds: Array<number>
  valueColors: boolean
  valueColorPositions?: JsChartExValueColorPositions
  shapeProperties?: JsChartShapeProperties
}

export interface JsChartExSeriesVisibility {
  connectorLines?: boolean
  meanLine?: boolean
  meanMarker?: boolean
  nonoutliers?: boolean
  outliers?: boolean
}

export interface JsChartExStatistics {
  quartileMethod?: string
}

export interface JsChartExText {
  formula?: string
  value?: string
}

export interface JsChartExTitle {
  text?: string
  position?: string
  align?: string
  overlay?: boolean
  offset?: JsChartExOffset
  shapeProperties?: JsChartShapeProperties
}

export interface JsChartExValueColorPositions {
  count?: number
  min?: JsChartExColorPosition
  mid?: JsChartExColorPosition
  max?: JsChartExColorPosition
}

/** Chart line overlay (drop lines, high-low lines, series lines). */
export interface JsChartLines {
  shapeProperties?: JsChartShapeProperties
}

/** A chart number format. */
export interface JsChartNumberFormat {
  formatCode: string
  sourceLinked?: boolean
}

/** Shape properties for chart elements. */
export interface JsChartShapeProperties {
  solidFillHex?: string
  noFill: boolean
  lineWidth?: number
  lineColorHex?: string
  lineNoFill: boolean
  lineDashStyle?: string
}

/** A chart sheet - a sheet that contains only a chart. */
export interface JsChartSheet {
  name: string
  chart: JsChart
  visibility: string
}

/**
 * A chart style part. `entries` is keyed by the element name the entry
 * belongs to (`chartArea`, `dataPoint`, ...); `raw` is set instead when
 * the part could not be modelled and is being replayed as read.
 */
export interface JsChartStyle {
  id?: number
  entries: Record<string, JsChartStyleEntry>
  markerSymbol?: string
  markerSize?: number
  raw?: string
}

export interface JsChartStyleEntry {
  lineReference: JsChartStyleReference
  lineWidthScale?: number
  fillReference: JsChartStyleReference
  effectReference: JsChartStyleReference
  /** `major`, `minor` or `none`. */
  fontCollection: string
  fontColor?: string
  /** DrawingML kept as the XML it was read as. */
  shapeProperties?: string
  defaultRunProperties?: string
  bodyProperties?: string
  mods?: string
}

export interface JsChartStyleReference {
  idx: number
  /** The colour override, as the XML it was read as. */
  color?: string
}

export interface JsChartTypeGroup {
  chartType: string
  is3D: boolean
  series: Array<JsDataSeries>
  dataLabels?: JsDataLabels
  varyColors?: boolean
  gapWidth?: number
  overlap?: number
  firstSliceAngle?: number
  holeSize?: number
  bubbleScale?: number
  showNegativeBubbles?: boolean
  radarStyle?: string
  wireframe?: boolean
  axisIds: Array<number>
  dropLines?: JsChartLines
  highLowLines?: JsChartLines
  seriesLines?: JsChartLines
  upDownBars?: JsUpDownBars
}

export type JsCheckState =  'unchecked'|
'checked'|
'mixed';

/**
 * Color representation. The `colorType` field indicates the variant:
 * `"auto"`, `"rgb"`, `"argb"`, `"theme"`, or `"indexed"`.
 * `hex` carries the context-free hex string; it is absent for
 * `"auto"` and `"theme"` colors, which have no fixed RGB without the
 * workbook - resolve those through `Workbook.resolveColor`.
 */
export interface JsColor {
  colorType: string
  /**
   * Context-free hex string (6 or 8 chars, no `#` prefix); absent
   * for auto and theme colors.
   */
  hex?: string
  r?: number
  g?: number
  b?: number
  a?: number
  /** Theme color index (0-11), present when `colorType === "theme"`. */
  themeIndex?: number
  /** OOXML tint fraction (-1.0 to 1.0), present when `colorType === "theme"`. */
  tint?: number
  /** Palette index, present when `colorType === "indexed"`. */
  paletteIndex?: number
}

/**
 * Color input for style setters. Mirrors `JsColor`, but all fields are optional
 * so callers can pass either a returned color object or a compact patch.
 */
export interface JsColorInput {
  colorType?: string
  hex?: string
  r?: number
  g?: number
  b?: number
  a?: number
  themeIndex?: number
  tint?: number
  paletteIndex?: number
}

/** A cell comment/note. */
export interface JsComment {
  author: string
  text: string
  visible: boolean
}

/** A comment with its cell address. */
export interface JsCommentEntry {
  row: number
  col: number
  comment: JsComment
}

/** A conditional formatting rule. */
export interface JsConditionalFormatRule {
  /**
   * The type of rule: `"cellIs"`, `"expression"`, `"colorScale"`, `"dataBar"`,
   * `"iconSet"`, `"top10"`, `"aboveAverage"`, `"containsText"`, `"beginsWith"`,
   * `"endsWith"`, `"duplicateValues"`, `"uniqueValues"`, `"containsBlanks"`,
   * `"notContainsBlanks"`, `"containsErrors"`, `"notContainsErrors"`, `"timePeriod"`.
   */
  ruleType: string
  /** Ranges this rule applies to (as range strings). */
  ranges: Array<string>
  /** Lower number = higher priority. */
  priority: number
  stopIfTrue: boolean
  /** Operator (present for `cellIs` rules). */
  operator?: string
  /** Formula/value (present for `cellIs`, `expression` rules). */
  formula1?: string
  formula2?: string
  /** Text value (present for `containsText`, `beginsWith`, `endsWith`). */
  text?: string
  /** Rank for top/bottom N rules. */
  rank?: number
  /** Whether the top/bottom N rule uses percentages. */
  percent?: boolean
  /** Whether it's a "bottom N" rule (vs top N). */
  bottom?: boolean
}

/** Data labels configuration. */
export interface JsDataLabels {
  showLegendKey?: boolean
  showValue?: boolean
  showCategoryName?: boolean
  showSeriesName?: boolean
  showPercent?: boolean
  showBubbleSize?: boolean
  separator?: string
  position?: string
  numberFormat?: JsChartNumberFormat
  showLeaderLines?: boolean
}

/** An individual data point override. */
export interface JsDataPoint {
  index: number
  marker?: JsMarker
  explosion?: number
  shapeProperties?: JsChartShapeProperties
}

/** Reference to chart data. */
export interface JsDataReference {
  /** One of: `"formula"`, `"numbers"`, `"strings"`. */
  refType: string
  formula?: string
  numbers?: Array<number>
  strings?: Array<string>
}

/** A chart data series. */
export interface JsDataSeries {
  name?: string
  values: JsDataReference
  categories?: JsDataReference
  dataLabels?: JsDataLabels
  trendline?: JsTrendline
  errorBars?: JsErrorBars
  marker?: JsMarker
  dataPoints: Array<JsDataPoint>
  smooth?: boolean
  explosion?: number
  invertIfNegative?: boolean
  shapeProperties?: JsChartShapeProperties
}

/** A data validation rule. */
export interface JsDataValidation {
  /**
   * The type of validation: `"none"`, `"whole"`, `"decimal"`, `"list"`,
   * `"date"`, `"time"`, `"textLength"`, `"custom"`.
   */
  validationType: string
  /** Ranges this validation applies to (as range strings). */
  ranges: Array<string>
  allowBlank: boolean
  showDropdown: boolean
  showInputMessage: boolean
  inputTitle?: string
  inputMessage?: string
  showErrorAlert: boolean
  /** `"stop"`, `"warning"`, or `"information"`. */
  errorStyle: string
  errorTitle?: string
  errorMessage?: string
  /**
   * Operator (present for numeric/date/time/textLength validations):
   * `"between"`, `"notBetween"`, `"equal"`, `"notEqual"`, `"greaterThan"`,
   * `"lessThan"`, `"greaterThanOrEqual"`, `"lessThanOrEqual"`.
   */
  operator?: string
  /** First value/formula (present for most validation types). */
  value1?: string
  /** Second value/formula (present for `between`/`notBetween`). */
  value2?: string
  /** List source string (present when `validationType === "list"`). */
  listSource?: string
  /** Custom formula (present when `validationType === "custom"`). */
  formula?: string
}

/** Error bars attached to a data series. */
export interface JsErrorBars {
  direction: string
  barType: string
  valueType: string
  value?: number
  noEndCap?: boolean
}

/**
 * Fill/background style. The `fillType` field indicates the variant:
 * `"none"`, `"solid"`, `"pattern"`, or `"gradient"`.
 */
export interface JsFillStyle {
  fillType: string
  /** Solid fill color (present when `fillType === "solid"`). */
  color?: JsColor
  /** Pattern type string (present when `fillType === "pattern"`). */
  pattern?: string
  /** Pattern foreground color. */
  foreground?: JsColor
  /** Pattern background color. */
  background?: JsColor
  /** Gradient type: `"linear"` or `"path"` (present when `fillType === "gradient"`). */
  gradientType?: string
  /** Gradient angle in degrees. */
  angle?: number
  /** Gradient color stops. */
  stops?: Array<JsGradientStop>
}

/** Fill/background input for style setters. */
export interface JsFillStylePatch {
  fillType?: string
  color?: JsColorInput
  pattern?: string
  foreground?: JsColorInput
  background?: JsColorInput
  gradientType?: string
  angle?: number
  stops?: Array<JsGradientStopInput>
}

/** A filter on a single column. */
export interface JsFilterColumn {
  colId: number
  hiddenButton: boolean
  showButton: boolean
  /** The type of filter: `"values"`, `"custom"`, `"top10"`, `"dynamic"`, or `"color"`. */
  filterType: string
  /** Values for a discrete value filter (present when `filterType === "values"`). */
  values?: Array<string>
  /** Include blanks (present when `filterType === "values"`). */
  blank?: boolean
}

/** Font style settings. */
export interface JsFontStyle {
  name: string
  size: number
  bold: boolean
  italic: boolean
  /** One of: `"none"`, `"single"`, `"double"`, `"singleAccounting"`, `"doubleAccounting"`. */
  underline: string
  strikethrough: boolean
  color: JsColor
  /** One of: `"baseline"`, `"superscript"`, `"subscript"`. */
  verticalAlign: string
  family?: number
  charset?: number
  scheme?: string
}

/** Font input for style setters. Missing fields leave the existing font setting unchanged. */
export interface JsFontStylePatch {
  name?: string
  size?: number
  bold?: boolean
  italic?: boolean
  underline?: string
  strikethrough?: boolean
  color?: JsColorInput
  verticalAlign?: string
  family?: number
  charset?: number
  scheme?: string
}

export interface JsFormControlInteractionResult {
  controlsChanged: number
  linkedCellsChanged: number
}

/** A formula cell with address. */
export interface JsFormulaCell {
  row: number
  col: number
  formula: string
}

/** Freeze pane settings. */
export interface JsFreezePanes {
  /** First unfrozen row. */
  row: number
  /** First unfrozen column. */
  col: number
}

/** Gradient color stop. */
export interface JsGradientStop {
  position: number
  color: JsColor
}

/** Gradient color stop input for style setters. */
export interface JsGradientStopInput {
  position: number
  color: JsColorInput
}

/** A hyperlink attached to a cell. */
export interface JsHyperlink {
  /** Target URL (external) or cell reference (internal). */
  target: string
  /** Display text (shown in cell; `null` means cell value is used). */
  display?: string
  /** Tooltip shown on hover. */
  tooltip?: string
  /** Location within target (e.g., sheet reference for internal links). */
  location?: string
}

/** A hyperlink with its cell address. */
export interface JsHyperlinkEntry {
  address: string
  hyperlink: JsHyperlink
}

/** IMAGE() metadata captured during calculation. */
export interface JsImageInfo {
  /** IMAGE source URL or path. */
  source: string
  /** IMAGE alternate text. */
  altText: string
  /** 0=FitCell, 1=FillCell, 2=OriginalSize, 3=Custom */
  sizing: number
  /** Optional custom width. */
  width?: number
  /** Optional custom height. */
  height?: number
}

/** Layout container. */
export interface JsLayout {
  manualLayout?: JsManualLayout
}

/** A chart legend. */
export interface JsLegend {
  /** One of: `"Right"`, `"Top"`, `"Bottom"`, `"Left"`, `"TopRight"`. */
  position: string
  overlay: boolean
}

export type JsListSelection =  'single'|
'multi'|
'extend';

/** Manual layout positioning. */
export interface JsManualLayout {
  x?: number
  y?: number
  width?: number
  height?: number
}

/** Marker for a data point. */
export interface JsMarker {
  symbol?: string
  size?: number
}

/** A merged cell region with structured coordinates. */
export interface JsMergedRegion {
  startRow: number
  startCol: number
  endRow: number
  endCol: number
  /** The range as an A1-style string (e.g., "A1:C3"). */
  range: string
}

/** The row/column span of a merged region's origin cell. */
export interface JsMergeSpan {
  rowSpan: number
  colSpan: number
}

/** A named range definition. */
export interface JsNamedRange {
  name: string
  /** `"workbook"` or `"sheet"`. */
  scope: string
  /** Sheet index when `scope === "sheet"`. */
  sheetIndex?: number
  /** The formula/reference the name refers to. */
  refersTo: string
  comment?: string
  hidden: boolean
}

/**
 * Number format. The `formatType` field indicates the variant:
 * `"general"`, `"builtin"`, or `"custom"`.
 */
export interface JsNumberFormat {
  formatType: string
  /** Built-in format ID (present when `formatType === "builtin"`). */
  id?: number
  /** The resolved format string (always present). */
  formatString: string
  /** Whether this format represents a date/time. */
  isDateFormat: boolean
}

/** Number format input for style setters. */
export interface JsNumberFormatPatch {
  formatType?: string
  id?: number
  formatString?: string
}

/** A manual page break (row or column). */
export interface JsPageBreak {
  /** Row index (for row breaks) or column index (for col breaks), 0-based. */
  id: number
  min: number
  max: number
  /** Whether this is a manual break. */
  manual: boolean
}

/** Page setup / print settings. */
export interface JsPageSetup {
  /** Paper size (1 = Letter, 9 = A4, etc.). */
  paperSize: number
  /** `"portrait"` or `"landscape"`. */
  orientation: string
  /** Scale percentage (10-400). */
  scale: number
  fitToWidth?: number
  fitToHeight?: number
  topMargin: number
  bottomMargin: number
  leftMargin: number
  rightMargin: number
  headerMargin: number
  footerMargin: number
  printGridlines: boolean
  printHeadings: boolean
  oddHeader?: string
  oddFooter?: string
  evenHeader?: string
  evenFooter?: string
  firstHeader?: string
  firstFooter?: string
  differentOddEven: boolean
  differentFirst: boolean
  scaleWithDoc: boolean
  alignWithMargins: boolean
}

/** Protected editable range settings. */
export interface JsProtectedRange {
  name: string
  ranges: Array<string>
  passwordHash?: number
  securityDescriptor?: string
}

/** Protected editable range setter input. */
export interface JsProtectedRangeInput {
  name: string
  ranges: Array<string>
  password?: string
  passwordHash?: number
  securityDescriptor?: string
}

/** A single run of rich text. */
export interface JsRichTextRun {
  text: string
  font?: JsRunFont
}

/** A sparse row containing only non-empty cells. */
export interface JsRow {
  /** Row index (0-based). */
  index: number
  /** Non-empty cells in this row, sorted by column. */
  cells: Array<JsRowCell>
}

/** A single cell within a sparse row. */
export interface JsRowCell {
  /** Column index (0-based). */
  col: number
  /** String representation of the cell value. */
  value: string
  /** Cell style (when includeStyles is set). */
  style?: JsStyle
  /** Merge span for merge-origin cells (when includeMergeInfo is set). */
  mergeSpan?: JsMergeSpan
  /** Whether this cell is a non-origin member of a merge (when includeMergeInfo is set). */
  isMergedSecondary?: boolean
  /** Hyperlink (when includeHyperlinks is set). */
  hyperlink?: JsHyperlink
  /** Comment (when includeComments is set). */
  comment?: JsComment
  /** Formula text (when includeFormulas is set). */
  formula?: string
  /** IMAGE() metadata (when includeImages is set). */
  image?: JsImageInfo
}

/** Options for row iteration. */
export interface JsRowsOptions {
  /** Use display-formatted values (e.g., "$1,234.56") instead of raw values. */
  useFormattedValues?: boolean
  /** Use calculated values for formula cells (requires prior calculate() call). */
  useCalculatedValues?: boolean
  /** Include cell styles. */
  includeStyles?: boolean
  /** Include merge info (mergeSpan + isMergedSecondary). */
  includeMergeInfo?: boolean
  /** Include hyperlinks. */
  includeHyperlinks?: boolean
  /** Include comments. */
  includeComments?: boolean
  /** Include formula text. */
  includeFormulas?: boolean
  /** Include IMAGE() metadata. */
  includeImages?: boolean
  /** Skip cells whose raw value is empty (CellValue::Empty). */
  skipEmptyValues?: boolean
  /** Skip cells whose raw value is blank (empty, empty string, or empty rich text). */
  skipBlankValues?: boolean
}

/** Font properties for a rich text run (all fields optional - unset inherits cell style). */
export interface JsRunFont {
  bold?: boolean
  italic?: boolean
  size?: number
  color?: JsColor
  name?: string
  underline?: string
  strikethrough?: boolean
  verticalAlign?: string
}

/** A selection within a sheet view. */
export interface JsSelection {
  pane?: string
  activeCell?: string
  sqref?: string
}

/** Sheet protection settings. */
export interface JsSheetProtection {
  protected: boolean
  passwordHash?: number
  selectLockedCells: boolean
  selectUnlockedCells: boolean
  formatCells: boolean
  formatColumns: boolean
  formatRows: boolean
  insertColumns: boolean
  insertRows: boolean
  insertHyperlinks: boolean
  deleteColumns: boolean
  deleteRows: boolean
  sort: boolean
  autoFilter: boolean
  pivotTables: boolean
}

/** Sheet protection setter input. */
export interface JsSheetProtectionInput {
  protected?: boolean
  password?: string
  passwordHash?: number
  selectLockedCells?: boolean
  selectUnlockedCells?: boolean
  formatCells?: boolean
  formatColumns?: boolean
  formatRows?: boolean
  insertColumns?: boolean
  insertRows?: boolean
  insertHyperlinks?: boolean
  deleteColumns?: boolean
  deleteRows?: boolean
  sort?: boolean
  autoFilter?: boolean
  pivotTables?: boolean
}

/** A slot in the workbook tab bar. */
export interface JsSheetSlot {
  /** `"worksheet"` or `"chartsheet"`. */
  slotType: string
  /** Index into the respective collection. */
  index: number
}

/** A cell with address and value. */
export interface JsSpillSource {
  row: number
  col: number
}

/** Split pane settings. */
export interface JsSplitPanes {
  xSplit: number
  ySplit: number
  topLeftRow?: number
  topLeftCol?: number
  activePane?: string
}

/**
 * Complete cell style including font, fill, border, alignment, number format,
 * and protection settings.
 */
export interface JsStyle {
  font: JsFontStyle
  fill: JsFillStyle
  border: JsBorderStyle
  alignment: JsAlignment
  numberFormat: JsNumberFormat
  protection: JsCellProtection
}

/**
 * Cell style input for style setters. A complete `JsStyle` returned from
 * `getCellStyle()` is assignable to this type; partial objects act as patches.
 */
export interface JsStylePatch {
  font?: JsFontStylePatch
  fill?: JsFillStylePatch
  border?: JsBorderStylePatch
  alignment?: JsAlignmentPatch
  numberFormat?: JsNumberFormatPatch
  protection?: JsCellProtectionPatch
}

/** An Excel table (ListObject). */
export interface JsTable {
  id: number
  name: string
  displayName: string
  /** Range string (e.g., `"A1:D10"`). */
  reference: string
  columns: Array<JsTableColumn>
  styleInfo?: JsTableStyleInfo
  headerRowCount: number
  totalsRowCount: number
  totalsRowShown: boolean
}

/** A column within a table. */
export interface JsTableColumn {
  id: number
  name: string
  /**
   * One of: `"average"`, `"count"`, `"countNums"`, `"max"`, `"min"`,
   * `"sum"`, `"stdDev"`, `"var"`, `"custom"`, `"none"`, or `null`.
   */
  totalsRowFunction?: string
  totalsRowFormula?: string
  totalsRowLabel?: string
  calculatedColumnFormula?: string
}

/** Table style configuration. */
export interface JsTableStyleInfo {
  name?: string
  showFirstColumn: boolean
  showLastColumn: boolean
  showRowStripes: boolean
  showColumnStripes: boolean
}

/** A trendline attached to a data series. */
export interface JsTrendline {
  trendlineType: string
  name?: string
  order?: number
  period?: number
  forward?: number
  backward?: number
  intercept?: number
  displayRSquared?: boolean
  displayEquation?: boolean
}

/** Up-down bars (stock charts). */
export interface JsUpDownBars {
  gapWidth?: number
  upBars?: JsChartLines
  downBars?: JsChartLines
}

/** 3D view settings. */
export interface JsView3D {
  rotateX?: number
  rotateY?: number
  depthPercent?: number
  heightPercent?: number
  perspective?: number
  rightAngleAxes?: boolean
}

/** Workbook protection settings. */
export interface JsWorkbookProtection {
  structure: boolean
  windows: boolean
  passwordHash?: number
}

/** Workbook protection setter input. */
export interface JsWorkbookProtectionInput {
  structure?: boolean
  windows?: boolean
  password?: string
  passwordHash?: number
}

/** Workbook-level settings. */
export interface JsWorkbookSettings {
  /** Whether the 1904 date system is used (macOS default). */
  date1904: boolean
  /** Whether the workbook structure is protected. */
  protected: boolean
  /** Calculate formulas on open. */
  calcOnOpen: boolean
  theme?: string
}

/**
 * Open a workbook from a file asynchronously (non-blocking).
 *
 * Runs file I/O and parsing on the libuv thread pool so the
 * Node.js event loop is not blocked.
 *
 * @param path - Path to the file
 * @returns Promise<Workbook>
 */
export declare function openAsync(path: string): Promise<Workbook>

/**
 * The used range of a worksheet, describing the bounding box of all cells
 * that contain data.
 */
export interface UsedRange {
  minRow: number
  minCol: number
  maxRow: number
  maxCol: number
}
