/**
 * Hand-maintained type definitions for @dukelib/sheets.
 *
 * Re-exports everything from generated.d.ts (auto-generated by napi build)
 * and adds manual types for JS-side classes and recursive drawing DTOs.
 */
export * from './generated'

import type * as Generated from './generated'
import type { JsRow, JsRowsOptions } from './generated'

/** Iterator over sparse rows. Batches FFI calls internally for performance. */
export declare class RowIterator implements IterableIterator<JsRow> {
  [Symbol.iterator](): IterableIterator<JsRow>
  next(): IteratorResult<JsRow>
}

export type JsChart = Omit<Generated.JsChart, 'anchor'>
export type JsChartSheet = Omit<Generated.JsChartSheet, 'chart'> & { chart: JsChart }

export interface DrawingMeta {
  name?: string
  hidden: boolean
  locked: boolean
  printable: boolean
  altText?: string
  title?: string
}

export interface DrawingMetaInput {
  name?: string
  hidden?: boolean
  locked?: boolean
  printable?: boolean
  altText?: string
  title?: string
}

/** A cell-relative anchor marker. Offsets are EMU within the cell and always present on output. */
export interface DrawingCellMarker {
  col: number
  row: number
  colOffsetEmu?: number
  rowOffsetEmu?: number
}

/** Anchor spanning two cell markers; `editAs` records the sizing behavior Excel applies on edit. */
export interface TwoCellAnchor {
  type: 'twoCell'
  from: DrawingCellMarker
  to: DrawingCellMarker
  editAs?: 'twoCell' | 'oneCell' | 'absolute'
}

/** Anchor pinned to one cell with a fixed EMU extent. */
export interface OneCellAnchor {
  type: 'oneCell'
  from: DrawingCellMarker
  widthEmu: number
  heightEmu: number
}

/** Anchor at a fixed EMU position and extent, independent of cells. */
export interface AbsoluteAnchor {
  type: 'absolute'
  xEmu: number
  yEmu: number
  widthEmu: number
  heightEmu: number
}

/** Drawing anchors preserve their file variant on read and accept any variant on write. */
export type DrawingAnchor = TwoCellAnchor | OneCellAnchor | AbsoluteAnchor

export interface DrawingChildTransform {
  xEmu?: number
  yEmu?: number
  cxEmu?: number
  cyEmu?: number
  rotation?: number
  flipH?: boolean
  flipV?: boolean
}

export interface DrawingGroupTransform extends DrawingChildTransform {
  childXEmu?: number
  childYEmu?: number
  childCxEmu?: number
  childCyEmu?: number
}

export type DrawingPlacement =
  | { anchor: DrawingAnchor; transform?: never }
  | { anchor?: never; transform: DrawingChildTransform }

export type DrawingColor =
  | { colorType: 'auto' }
  | { colorType: 'rgb'; r: number; g: number; b: number }
  | { colorType: 'argb'; a: number; r: number; g: number; b: number }
  | { colorType: 'theme'; index: number; tint: number }
  | { colorType: 'indexed'; index: number }

export interface DrawingRunFont {
  bold?: boolean
  italic?: boolean
  size?: number
  color?: DrawingColor
  name?: string
  underline?: 'none' | 'single' | 'double' | 'singleAccounting' | 'doubleAccounting'
  strikethrough?: boolean
  verticalAlign?: 'baseline' | 'superscript' | 'subscript'
  family?: number
  charset?: number
  scheme?: string
}

export interface DrawingText {
  runs: Array<{ text: string; font?: DrawingRunFont }>
  horizontalAlignment?: 'general' | 'left' | 'center' | 'right' | 'fill' | 'justify' | 'centerContinuous' | 'distributed'
  verticalAlignment?: 'top' | 'center' | 'bottom' | 'justify' | 'distributed'
}

export type FormControlKind =
  | { kind: 'button'; caption: DrawingText }
  | { kind: 'checkbox'; caption: DrawingText; state: 'unchecked' | 'checked' | 'mixed'; cellLink?: string; no3D: boolean }
  /**
   * `firstInGroup` reports whether this radio heads its group; writers
   * recompute it from group-box containment, so it is read-side
   * information. `'mixed'` never validates on write but can surface
   * when reading hostile files.
   */
  | { kind: 'optionButton'; caption: DrawingText; state: 'unchecked' | 'checked' | 'mixed'; cellLink?: string; firstInGroup: boolean; no3D: boolean }
  | { kind: 'label'; caption: DrawingText }
  | { kind: 'groupBox'; caption: DrawingText; no3D: boolean }
  | { kind: 'listBox'; inputRange?: string; cellLink?: string; selection: 'single' | 'multi' | 'extend'; selected: number[]; no3D: boolean }
  | { kind: 'dropdown'; inputRange?: string; cellLink?: string; selected?: number; lines: number; no3D: boolean }
  | { kind: 'scrollbar'; value: number; min: number; max: number; increment: number; page: number; horizontal: boolean; cellLink?: string }
  | { kind: 'spinner'; value: number; min: number; max: number; increment: number; cellLink?: string }
  /** Unsupported legacy control, preserved for passthrough. */
  | { kind: 'unknown'; objectType: string; legacyObjectType?: number; caption: DrawingText }

export type FormControlKindInput =
  | { kind: 'button'; caption: DrawingText }
  | { kind: 'checkbox'; caption: DrawingText; state: 'unchecked' | 'checked' | 'mixed'; cellLink?: string; no3D?: boolean }
  /** `firstInGroup` is ignored on input; writers recompute it from group-box containment. */
  | { kind: 'optionButton'; caption: DrawingText; state: 'unchecked' | 'checked'; cellLink?: string; firstInGroup?: boolean; no3D?: boolean }
  | { kind: 'label'; caption: DrawingText }
  | { kind: 'groupBox'; caption: DrawingText; no3D?: boolean }
  | { kind: 'listBox'; inputRange?: string; cellLink?: string; selection: 'single' | 'multi' | 'extend'; selected?: number[]; no3D?: boolean }
  | { kind: 'dropdown'; inputRange?: string; cellLink?: string; selected?: number; lines: number; no3D?: boolean }
  | { kind: 'scrollbar'; value: number; min: number; max: number; increment: number; page: number; horizontal?: boolean; cellLink?: string }
  | { kind: 'spinner'; value: number; min: number; max: number; increment: number; cellLink?: string }
  | { kind: 'unknown'; objectType: string; legacyObjectType?: number; caption?: DrawingText }

export interface FormControlPayload {
  kind: FormControlKind
  macroName?: string
  /**
   * Unmodeled VML ClientData child fragments preserved on any control
   * kind (`<x:Disabled/>`, button dialog semantics, ...); opaque
   * internal passthrough echoed back unchanged on write.
   */
  rawClientData: Buffer[]
  /**
   * Unmodeled XLSX formControlPr attributes preserved on any control
   * kind; opaque internal passthrough echoed back unchanged on write.
   */
  rawProperties: Array<[string, string]>
  /** Original BIFF OBJ body for XLS passthrough of unknown controls. */
  rawObj?: Buffer
}

export interface FormControlInputPayload {
  kind: FormControlKindInput
  macroName?: string
  /** Echo back the raw* fields unchanged when rewriting a control read from a file. */
  rawClientData?: Buffer[]
  rawProperties?: Array<[string, string]>
  rawObj?: Buffer
}

export interface DrawingImage {
  format: 'png' | 'jpeg' | 'gif' | 'bmp' | 'emf' | 'wmf' | 'tiff' | 'svg'
  mediaPath: string
  svgMediaPath?: string
  widthEmu: number
  heightEmu: number
  rotation?: number
  flipH: boolean
  flipV: boolean
}

export interface DrawingImageInput extends Partial<Omit<DrawingImage, 'format' | 'widthEmu' | 'heightEmu'>> {
  format: DrawingImage['format']
  widthEmu: number
  heightEmu: number
  data: Buffer
  svgData?: Buffer
}

export type DrawingShapeFill =
  | { kind: 'none' }
  | { kind: 'solid'; color: DrawingColor }

export interface DrawingShape {
  geometry: string
  fill: DrawingShapeFill
  line: { color?: DrawingColor; widthEmu?: number; dashStyle?: string; noFill: boolean }
  text?: DrawingText
  rotation: number
  flipH: boolean
  flipV: boolean
}

export interface DrawingShapeInput extends Partial<DrawingShape> {
  geometry?: string
}

export interface DrawingComment {
  row: number
  col: number
  author: string
  /** Plain text (runs concatenated). */
  text: string
  /**
   * Rich runs; present on output when any run is formatted, and wins
   * over `text` on input when supplied.
   */
  richText?: DrawingText
}

export type ChartDataReferenceInput =
  | { refType: 'formula'; formula: string }
  | { refType: 'numbers'; numbers: number[] }
  | { refType: 'strings'; strings: string[] }

export interface ChartSeriesInput {
  name?: string
  values: ChartDataReferenceInput
  categories?: ChartDataReferenceInput
}

/** Exactly the chart fields accepted when authoring; all other JsChart fields are read-only. */
export interface ChartInput {
  chartType: string
  title?: string
  series?: ChartSeriesInput[]
  is3D?: boolean
  varyColors?: boolean
  gapWidth?: number
  overlap?: number
}

export interface ChartExTitleInput {
  text?: string
  position?: string
  align?: string
  overlay?: boolean
}

/** Exactly the ChartEx fields accepted when authoring; all other JsChartEx fields are read-only. */
export interface ChartExInput {
  layout: string
  version?: string
  featureList?: string
  fallbackImg?: string
  title?: ChartExTitleInput
}

export interface RawDrawingRelationshipMetadata {
  id: string
  relType: string
  target: string
  external: boolean
  hasPart: boolean
}

export interface RawDrawingMetadata {
  byteLength: number
  relationships: RawDrawingRelationshipMetadata[]
}

/**
 * Resolved on-sheet placement in EMU: the anchor rectangle for
 * top-level drawings, the group-mapped (rotation/flip aware)
 * rectangle for group children.
 */
export type RectEmu = { xEmu: number; yEmu: number; widthEmu: number; heightEmu: number }

type DrawingNode = DrawingMeta & DrawingPlacement & { drawingPath: number[]; absoluteRectEmu: RectEmu }

export type DrawnImage = DrawingNode & { kind: 'image'; image: DrawingImage }
export type DrawnChart = DrawingNode & { kind: 'chart'; chart: JsChart }
export type DrawnChartEx = DrawingNode & { kind: 'chartEx'; chartEx: JsChartEx }
export type DrawnFormControl = DrawingNode & { kind: 'formControl'; formControl: FormControlPayload }
export type DrawnComment = DrawingNode & { kind: 'comment'; comment: DrawingComment }
export type DrawnShape = DrawingNode & { kind: 'shape'; shape: DrawingShape }
export type DrawnGroup = DrawingNode & { kind: 'group'; group: { groupTransform: DrawingGroupTransform; children: Drawing[] } }
export type DrawnRaw = DrawingNode & { kind: 'raw'; raw: RawDrawingMetadata }

export type Drawing = DrawnImage | DrawnChart | DrawnChartEx | DrawnFormControl | DrawnComment | DrawnShape | DrawnGroup | DrawnRaw

type DrawingInputPayload =
  | { kind: 'image'; image: DrawingImageInput }
  | { kind: 'chart'; chart: ChartInput }
  | { kind: 'chartEx'; chartEx: ChartExInput }
  | { kind: 'formControl'; formControl: FormControlInputPayload }
  | { kind: 'comment'; comment: DrawingComment }
  | { kind: 'shape'; shape: DrawingShapeInput }
  | { kind: 'group'; group: { groupTransform?: DrawingGroupTransform; children?: DrawingInput[] } }

export type TopLevelDrawingInput = DrawingMetaInput & {
  anchor: DrawingAnchor
  transform?: never
} & DrawingInputPayload

export type GroupChildDrawingInput = DrawingMetaInput & {
  anchor?: never
  transform: DrawingChildTransform
} & DrawingInputPayload

export type DrawingInput = TopLevelDrawingInput | GroupChildDrawingInput

export interface FormControlInteractionResult {
  controlsChanged: number
  linkedCellsChanged: number
}

type ReplacedWorksheetMembers =
  | 'drawings'
  | 'charts'
  | 'chartCount'
  | 'chartsEx'
  | 'chartExCount'
  | 'images'
  | 'imageCount'
  | 'formControls'
  | 'formControlCount'
  | 'addFormControl'
  | 'setFormControl'
  | 'removeFormControl'
  | 'addDrawing'
  | 'insertDrawing'
  | 'setDrawing'
  | 'removeDrawing'
  | 'moveDrawing'
  | 'drawingImageData'
  | 'drawingSvgData'
  | 'setFormControlCheckState'

export type Worksheet = Omit<Generated.Worksheet, ReplacedWorksheetMembers> & {
  /** Iterate over sparse rows, batching native calls internally. */
  iterateRows(opts?: JsRowsOptions): RowIterator
  readonly drawings: Drawing[]
  readonly formControls: DrawnFormControl[]
  readonly formControlCount: number
  readonly images: DrawnImage[]
  readonly imageCount: number
  readonly charts: DrawnChart[]
  readonly chartCount: number
  readonly chartsEx: DrawnChartEx[]
  readonly chartExCount: number
  addDrawing(input: TopLevelDrawingInput): number
  /** Drawing paths are positional; mutating the list invalidates previously returned paths. */
  insertDrawing(index: number, input: TopLevelDrawingInput): void
  /** Drawing paths are positional; mutating the list invalidates previously returned paths. */
  setDrawing(path: number[], input: DrawingInput): void
  /** Drawing paths are positional; mutating the list invalidates previously returned paths. */
  removeDrawing(path: number[]): void
  /** Drawing paths are positional; mutating the list invalidates previously returned paths. */
  moveDrawing(from: number, to: number): void
  /** Paths are positional; mutating the drawing list invalidates previously returned paths. */
  drawingImageData(path: number[]): Buffer
  /** Paths are positional; mutating the drawing list invalidates previously returned paths. */
  drawingSvgData(path: number[]): Buffer | null
  setFormControlCheckState(path: number[], state: Generated.JsCheckState): FormControlInteractionResult
}

export declare const Worksheet: {
  readonly prototype: Worksheet
}

export type Workbook = Omit<
  Generated.Workbook,
  'getSheet' | 'chartsheets' | 'syncFormControls' | 'syncFormControlsFromLinkedCells' | 'resolveColor'
> & {
  getSheet(indexOrName: number | string): Worksheet
  readonly chartsheets: JsChartSheet[]
  syncFormControls(): number
  syncFormControlsFromLinkedCells(): number
  /**
   * Resolve a drawing color to display RGB ("RRGGBB" hex) against
   * this workbook's theme palette; `auto` resolves to null.
   */
  resolveColor(color: DrawingColor): string | null
}

export declare const Workbook: {
  readonly prototype: Workbook
  new (): Workbook
  open(path: string): Workbook
  fromBytes(data: Buffer): Workbook
  fromCsvString(csv: string): Workbook
  openWithPassword(path: string, password: string, skipIntegrityCheck?: boolean | null): Workbook
}

export declare function openAsync(path: string): Promise<Workbook>
export declare function fromBytesAsync(data: Buffer): Promise<Workbook>
