//! End-to-end tests for password-protected XLS reading.
//!
//! Two fixtures cover both RC4 variants in our support matrix:
//!
//! - `xls_rc4_cryptoapi.xls` — generated by LibreOffice's `storeToURL`
//!   with a password. Despite the filename, this is actually the
//!   *legacy* MD5 RC4 path (FilePass `vMajor=1, vMinor=1`); LO emits
//!   that variant for `.xls` for Office 97/2000 compatibility.
//!
//! - `xls_rc4_cryptoapi_excel.xls` — generated by real Excel with
//!   `SetPasswordEncryptionOptions` set to "Microsoft Enhanced
//!   Cryptographic Provider v1.0" + RC4 + 128-bit. This is the modern
//!   CryptoAPI variant (FilePass `vMajor=4, vMinor=2`, SHA-1 KDF).
//!
//! Both fixtures are gitignored; tests skip cleanly if a fixture is
//! absent. Generate them with:
//!   - LO variant: `mise run crypto:fixtures`
//!   - Excel variant: `mise run crypto:fixtures:excel` (requires VM up)

use std::path::PathBuf;

use duke_sheets_xls::{XlsError, XlsReadOptions, XlsReader};

fn fixture(name: &str) -> Option<PathBuf> {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("..");
    p.push("duke-sheets-crypto");
    p.push("tests/fixtures");
    p.push(name);
    p.canonicalize().ok()
}

const FIXTURE_PASSWORD: &str = "duke-test-pw";

fn skip_if_missing(name: &str) -> Option<PathBuf> {
    let Some(p) = fixture(name) else {
        eprintln!(
            "SKIP: {name} not present; run `mise run crypto:fixtures` (or `crypto:fixtures:excel`)"
        );
        return None;
    };
    Some(p)
}

fn assert_decrypted_workbook(workbook: &duke_sheets_core::workbook::Workbook) {
    let sheet = workbook.worksheet(0).expect("sheet 0");
    let a1 = sheet.get_value("A1").expect("A1 must exist");
    let b1 = sheet.get_value("B1").expect("B1 must exist");
    assert_eq!(a1.as_string().as_deref(), Some("hello crypto"), "A1 value");
    assert_eq!(b1.as_number(), Some(42.0), "B1 value");
}

#[test]
fn legacy_rc4_md5_fails_without_password() {
    let Some(path) = skip_if_missing("xls_rc4_cryptoapi.xls") else {
        return;
    };
    let err = XlsReader::read_file(&path).expect_err("must be encrypted");
    assert!(
        matches!(err, XlsError::Encrypted(_)),
        "expected Encrypted, got {err:?}"
    );
}

#[test]
fn legacy_rc4_md5_decrypts_with_correct_password() {
    let Some(path) = skip_if_missing("xls_rc4_cryptoapi.xls") else {
        return;
    };
    let workbook = XlsReader::read_file_with(&path, &XlsReadOptions { password: Some(FIXTURE_PASSWORD.to_string()), ..Default::default() })
        .expect("decryption with correct password must succeed");
    assert_decrypted_workbook(&workbook);
}

#[test]
fn legacy_rc4_md5_wrong_password_yields_bad_password() {
    let Some(path) = skip_if_missing("xls_rc4_cryptoapi.xls") else {
        return;
    };
    let err = XlsReader::read_file_with(&path, &XlsReadOptions { password: Some("wrong-password".to_string()), ..Default::default() })
        .expect_err("must reject wrong password");
    assert!(
        matches!(err, XlsError::BadPassword),
        "expected BadPassword, got {err:?}"
    );
}

#[test]
fn cryptoapi_sha1_fails_without_password() {
    let Some(path) = skip_if_missing("xls_rc4_cryptoapi_excel.xls") else {
        return;
    };
    let err = XlsReader::read_file(&path).expect_err("must be encrypted");
    assert!(
        matches!(err, XlsError::Encrypted(_)),
        "expected Encrypted, got {err:?}"
    );
}

#[test]
fn cryptoapi_sha1_decrypts_with_correct_password() {
    let Some(path) = skip_if_missing("xls_rc4_cryptoapi_excel.xls") else {
        return;
    };
    let workbook = XlsReader::read_file_with(&path, &XlsReadOptions { password: Some(FIXTURE_PASSWORD.to_string()), ..Default::default() })
        .expect("decryption with correct password must succeed");
    assert_decrypted_workbook(&workbook);
}

#[test]
fn cryptoapi_sha1_wrong_password_yields_bad_password() {
    let Some(path) = skip_if_missing("xls_rc4_cryptoapi_excel.xls") else {
        return;
    };
    let err = XlsReader::read_file_with(&path, &XlsReadOptions { password: Some("wrong-password".to_string()), ..Default::default() })
        .expect_err("must reject wrong password");
    assert!(
        matches!(err, XlsError::BadPassword),
        "expected BadPassword, got {err:?}"
    );
}

#[test]
fn plain_xls_password_ignored() {
    let Some(path) = skip_if_missing("xls_rc4_cryptoapi.plain.xls") else {
        return;
    };
    let workbook = XlsReader::read_file_with(&path, &XlsReadOptions { password: Some("anything".to_string()), ..Default::default() })
        .expect("plain file should open regardless of password arg");
    assert!(workbook.sheet_count() >= 1);
}
