//! Round-trip tests for embedded PNG images in XLS.
//!
//! Exercises the in-process loop: build a workbook with an
//! `EmbeddedImage`, write to BIFF8 bytes, read back, assert the
//! image survives with its anchor + format + raw payload bytes
//! intact.

use std::io::Cursor;

use duke_sheets_chart::{CellMarker, DrawingAnchor, EditAs, EmbeddedImage, ImageFormat};
use duke_sheets_core::{DrawingObject, Placed, Workbook, Worksheet};
use duke_sheets_xls::{XlsReader, XlsWriter};

/// A 68-byte 1x1 transparent PNG with verified chunk CRCs, used as
/// the deterministic image payload for these tests.
const TEST_PNG_1X1: &[u8] = &[
    0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52,
    0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06, 0x00, 0x00, 0x00, 0x1F, 0x15, 0xC4,
    0x89, 0x00, 0x00, 0x00, 0x0B, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9C, 0x63, 0x60, 0x00, 0x02, 0x00,
    0x00, 0x05, 0x00, 0x01, 0x7A, 0x5E, 0xAB, 0x3F, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44,
    0xAE, 0x42, 0x60, 0x82,
];

fn write_then_read(wb: &Workbook) -> Workbook {
    let bytes = XlsWriter::write_to_bytes(wb).expect("serialize");
    XlsReader::read(Cursor::new(&bytes)).expect("read back")
}

fn images_of(ws: &Worksheet) -> Vec<Placed<'_, EmbeddedImage>> {
    ws.images().collect()
}

fn test_anchor(from_col: u16, from_row: u32) -> DrawingAnchor {
    DrawingAnchor::TwoCell {
        from: CellMarker {
            col: from_col,
            col_offset_emu: 0,
            row: from_row,
            row_offset_emu: 0,
        },
        to: CellMarker {
            col: from_col + 3,
            col_offset_emu: 0,
            row: from_row + 5,
            row_offset_emu: 0,
        },
        edit_as: None,
    }
}

fn test_payload(format: ImageFormat, data: &[u8]) -> EmbeddedImage {
    EmbeddedImage {
        format,
        media_path: String::new(),
        svg_media_path: None,
        width_emu: 1_000_000,
        height_emu: 1_000_000,
        rotation: None,
        flip_h: false,
        flip_v: false,
        data: data.to_vec(),
        svg_data: None,
    }
}

fn test_image(name: &str, from_col: u16, from_row: u32) -> DrawingObject {
    test_image_with_format(name, from_col, from_row, ImageFormat::Png, TEST_PNG_1X1)
}

fn test_image_with_format(
    name: &str,
    from_col: u16,
    from_row: u32,
    format: ImageFormat,
    data: &[u8],
) -> DrawingObject {
    DrawingObject::image(test_payload(format, data))
        .with_anchor(test_anchor(from_col, from_row))
        .with_name(name)
}

/// 632-byte 1x1 RGB JPEG at quality 50, generated by Python's PIL.
/// Valid enough for Excel and other decoders to retain on re-save
/// (a smaller cooked-up JPEG was silently dropped by Excel during
/// the SaveAs round-trip).
const TEST_JPEG_1X1: &[u8] = &[
    0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10, 0x4A, 0x46, 0x49, 0x46, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01,
    0x00, 0x01, 0x00, 0x00, 0xFF, 0xDB, 0x00, 0x43, 0x00, 0x10, 0x0B, 0x0C, 0x0E, 0x0C, 0x0A, 0x10,
    0x0E, 0x0D, 0x0E, 0x12, 0x11, 0x10, 0x13, 0x18, 0x28, 0x1A, 0x18, 0x16, 0x16, 0x18, 0x31, 0x23,
    0x25, 0x1D, 0x28, 0x3A, 0x33, 0x3D, 0x3C, 0x39, 0x33, 0x38, 0x37, 0x40, 0x48, 0x5C, 0x4E, 0x40,
    0x44, 0x57, 0x45, 0x37, 0x38, 0x50, 0x6D, 0x51, 0x57, 0x5F, 0x62, 0x67, 0x68, 0x67, 0x3E, 0x4D,
    0x71, 0x79, 0x70, 0x64, 0x78, 0x5C, 0x65, 0x67, 0x63, 0xFF, 0xDB, 0x00, 0x43, 0x01, 0x11, 0x12,
    0x12, 0x18, 0x15, 0x18, 0x2F, 0x1A, 0x1A, 0x2F, 0x63, 0x42, 0x38, 0x42, 0x63, 0x63, 0x63, 0x63,
    0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63,
    0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63,
    0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0xFF, 0xC0,
    0x00, 0x11, 0x08, 0x00, 0x01, 0x00, 0x01, 0x03, 0x01, 0x22, 0x00, 0x02, 0x11, 0x01, 0x03, 0x11,
    0x01, 0xFF, 0xC4, 0x00, 0x1F, 0x00, 0x00, 0x01, 0x05, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09,
    0x0A, 0x0B, 0xFF, 0xC4, 0x00, 0xB5, 0x10, 0x00, 0x02, 0x01, 0x03, 0x03, 0x02, 0x04, 0x03, 0x05,
    0x05, 0x04, 0x04, 0x00, 0x00, 0x01, 0x7D, 0x01, 0x02, 0x03, 0x00, 0x04, 0x11, 0x05, 0x12, 0x21,
    0x31, 0x41, 0x06, 0x13, 0x51, 0x61, 0x07, 0x22, 0x71, 0x14, 0x32, 0x81, 0x91, 0xA1, 0x08, 0x23,
    0x42, 0xB1, 0xC1, 0x15, 0x52, 0xD1, 0xF0, 0x24, 0x33, 0x62, 0x72, 0x82, 0x09, 0x0A, 0x16, 0x17,
    0x18, 0x19, 0x1A, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2A, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A,
    0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4A, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5A,
    0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6A, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7A,
    0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99,
    0x9A, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7,
    0xB8, 0xB9, 0xBA, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xD2, 0xD3, 0xD4, 0xD5,
    0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xF1,
    0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFF, 0xC4, 0x00, 0x1F, 0x01, 0x00, 0x03,
    0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
    0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0xFF, 0xC4, 0x00, 0xB5, 0x11, 0x00,
    0x02, 0x01, 0x02, 0x04, 0x04, 0x03, 0x04, 0x07, 0x05, 0x04, 0x04, 0x00, 0x01, 0x02, 0x77, 0x00,
    0x01, 0x02, 0x03, 0x11, 0x04, 0x05, 0x21, 0x31, 0x06, 0x12, 0x41, 0x51, 0x07, 0x61, 0x71, 0x13,
    0x22, 0x32, 0x81, 0x08, 0x14, 0x42, 0x91, 0xA1, 0xB1, 0xC1, 0x09, 0x23, 0x33, 0x52, 0xF0, 0x15,
    0x62, 0x72, 0xD1, 0x0A, 0x16, 0x24, 0x34, 0xE1, 0x25, 0xF1, 0x17, 0x18, 0x19, 0x1A, 0x26, 0x27,
    0x28, 0x29, 0x2A, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49,
    0x4A, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5A, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69,
    0x6A, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7A, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88,
    0x89, 0x8A, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6,
    0xA7, 0xA8, 0xA9, 0xAA, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xC2, 0xC3, 0xC4,
    0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xE2,
    0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9,
    0xFA, 0xFF, 0xDA, 0x00, 0x0C, 0x03, 0x01, 0x00, 0x02, 0x11, 0x03, 0x11, 0x00, 0x3F, 0x00, 0xC5,
    0xA2, 0x8A, 0x2B, 0xCB, 0x3E, 0xF0, 0xFF, 0xD9,
];

#[test]
fn large_images_round_trip_via_continue_records() {
    // Realistic images exceed the 8224-byte BIFF record body cap, so
    // MSODRAWINGGROUP (which carries every blip's bytes) must be split
    // across CONTINUE records. 20 KB covers the >8224 case; 80 KB also
    // covers bodies whose length cannot be represented in the record's
    // u16 size field at all.
    for size in [20_000usize, 80_000] {
        let mut data = TEST_PNG_1X1.to_vec();
        data.resize(size, 0xAB);

        let mut wb = Workbook::new();
        let ws = wb.worksheet_mut(0).unwrap();
        ws.add_drawing(test_image_with_format("Big", 1, 1, ImageFormat::Png, &data)).unwrap();

        let parsed = write_then_read(&wb);
        let images = images_of(parsed.worksheet(0).unwrap());
        assert_eq!(images.len(), 1, "{size}-byte image must survive round-trip");
        assert_eq!(
            images[0].payload.data(),
            &data[..],
            "{size}-byte image bytes must survive CONTINUE splitting"
        );
    }
}

#[test]
fn single_picture_round_trips() {
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.set_cell_value("A1", "anchor").expect("A1");
    ws.add_drawing(test_image("Picture 1", 2, 3)).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    assert_eq!(images.len(), 1, "picture must survive round-trip");

    let img = &images[0];
    assert_eq!(img.payload.format, ImageFormat::Png);
    assert_eq!(
        img.payload.data, TEST_PNG_1X1,
        "PNG bytes must round-trip verbatim"
    );
    assert_eq!(img.object.unwrap().meta.name.as_deref(), Some("Picture 1"));
    if let DrawingAnchor::TwoCell { from, to, .. } = &img.object.unwrap().anchor {
        assert_eq!(from.col, 2);
        assert_eq!(from.row, 3);
        assert_eq!(to.col, 5);
        assert_eq!(to.row, 8);
    } else {
        panic!("expected TwoCell anchor, got {:?}", img.object.unwrap().anchor);
    }
}

#[test]
fn xls_top_level_width_emu_does_not_survive_user_value() {
    // **Documented limitation.** EmbeddedImage.width_emu /
    // height_emu (the top-level fields, not the OneCell/Absolute
    // variant's inner width_emu/height_emu) are NOT preserved
    // through the XLS writer. The writer only encodes the anchor
    // cells and within-cell EMU offsets; the reader synthesises
    // top-level width_emu/height_emu from the anchor cell range
    // using default cell sizes (609,600 EMU per column, 190,500
    // per row).
    //
    // A user who sets a top-level width_emu = 7_500_000 (arbitrary
    // value) with a TwoCell anchor spanning 3 cols × 2 rows of
    // default cells will see width_emu = 3 × 609,600 = 1_828_800
    // on round-trip — their value is silently replaced.
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    let mut payload = test_payload(ImageFormat::Png, TEST_PNG_1X1);
    payload.width_emu = 7_500_000; // user-supplied non-default value
    payload.height_emu = 4_500_000;
    let anchor = DrawingAnchor::TwoCell {
        from: CellMarker {
            col: 0,
            col_offset_emu: 0,
            row: 0,
            row_offset_emu: 0,
        },
        to: CellMarker {
            col: 3,
            col_offset_emu: 0,
            row: 2,
            row_offset_emu: 0,
        },
        edit_as: None,
    };
    ws.add_drawing(
        DrawingObject::image(payload)
            .with_anchor(anchor)
            .with_name("Pic"),
    ).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    let out = images[0].payload;

    // The user's 7,500,000 / 4,500,000 are NOT preserved. Instead,
    // width_emu becomes 3 cols × 609,600 = 1,828,800 and
    // height_emu becomes 2 rows × 190,500 = 381,000.
    assert_eq!(
        out.width_emu, 1_828_800,
        "top-level width_emu is overwritten by synthesised value (3 cols × default cell width)"
    );
    assert_eq!(
        out.height_emu, 381_000,
        "top-level height_emu is overwritten by synthesised value (2 rows × default row height)"
    );
    assert_ne!(
        out.width_emu, 7_500_000,
        "the user's input width_emu is silently lost — documented limitation"
    );
}

#[test]
fn rotation_and_flip_flags_round_trip() {
    // Picture with 90 degree clockwise rotation (60000ths of degree
    // = 5,400,000), horizontal flip, vertical flip.
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    let mut payload = test_payload(ImageFormat::Png, TEST_PNG_1X1);
    payload.rotation = Some(5_400_000);
    payload.flip_h = true;
    payload.flip_v = true;
    ws.add_drawing(
        DrawingObject::image(payload)
            .with_anchor(test_anchor(1, 2))
            .with_name("Picture 1"),
    ).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    let img = images[0].payload;
    assert_eq!(img.rotation, Some(5_400_000), "rotation must round-trip");
    assert!(img.flip_h, "flip_h must round-trip");
    assert!(img.flip_v, "flip_v must round-trip");
}

#[test]
fn no_rotation_no_flip_round_trips_clean() {
    // Picture with default orientation must round-trip with rotation=None,
    // flip_h=false, flip_v=false (FOPT 0x0004 entry must be omitted).
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_drawing(test_image("Picture 1", 0, 0)).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    let img = images[0].payload;
    assert_eq!(img.rotation, None, "rotation must stay None");
    assert!(!img.flip_h, "flip_h must stay false");
    assert!(!img.flip_v, "flip_v must stay false");
}

#[test]
fn twocell_anchor_edit_as_collapses_to_default() {
    // editAs=TwoCell and editAs=None both map to ClientAnchor flag=0
    // (move+resize with cells) — the byte layout cannot distinguish
    // them, and they mean the same thing. The reader normalises
    // flag=0 to None so the model default round-trips exactly.
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_drawing(test_image("Picture 1", 1, 2).with_anchor(DrawingAnchor::TwoCell {
        from: CellMarker {
            col: 1,
            col_offset_emu: 0,
            row: 2,
            row_offset_emu: 0,
        },
        to: CellMarker {
            col: 4,
            col_offset_emu: 0,
            row: 7,
            row_offset_emu: 0,
        },
        edit_as: Some(EditAs::TwoCell),
    })).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    if let DrawingAnchor::TwoCell { edit_as, .. } = &images[0].object.unwrap().anchor {
        assert_eq!(*edit_as, None);
    } else {
        panic!("expected TwoCell");
    }
}

#[test]
fn onecell_anchor_round_trips_with_visual_area_preserved() {
    // OneCell input: from cell + width/height in EMU.
    // Writer encodes this as a TwoCell-style ClientAnchor with
    // flag=2 (move only). Reader maps flag=2 back to TwoCell with
    // editAs=OneCell. The variant tag is lost but the visual area
    // is preserved.
    const COL_EMU: i64 = 609_600;
    const ROW_EMU: i64 = 190_500;
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_drawing(test_image("Picture 1", 0, 0).with_anchor(DrawingAnchor::OneCell {
        from: CellMarker {
            col: 2,
            col_offset_emu: 0,
            row: 3,
            row_offset_emu: 0,
        },
        // Exactly 3 columns × 2 rows worth of default cells.
        width_emu: 3 * COL_EMU,
        height_emu: 2 * ROW_EMU,
    })).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    let img = &images[0];
    match &img.object.unwrap().anchor {
        DrawingAnchor::TwoCell {
            from,
            to,
            edit_as,
        } => {
            assert_eq!(from.col, 2);
            assert_eq!(from.row, 3);
            assert_eq!(to.col, 5, "OneCell width must extend by 3 cols");
            assert_eq!(to.row, 5, "OneCell height must extend by 2 rows");
            assert_eq!(*edit_as, Some(EditAs::OneCell));
        }
        other => panic!("expected TwoCell with editAs=OneCell, got {other:?}"),
    }
    assert_eq!(img.payload.width_emu, 3 * COL_EMU);
    assert_eq!(img.payload.height_emu, 2 * ROW_EMU);
}

#[test]
fn absolute_anchor_round_trips_with_visual_area_preserved() {
    // Absolute input: explicit x/y position + width/height in EMU.
    // Writer encodes this as a TwoCell-style ClientAnchor with
    // flag=3 (no move, no resize). Reader maps flag=3 back to
    // TwoCell with editAs=Absolute.
    const COL_EMU: i64 = 609_600;
    const ROW_EMU: i64 = 190_500;
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_drawing(test_image("Picture 1", 0, 0).with_anchor(DrawingAnchor::Absolute {
        x_emu: 4 * COL_EMU,
        y_emu: 3 * ROW_EMU,
        width_emu: 2 * COL_EMU,
        height_emu: 4 * ROW_EMU,
    })).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    match &images[0].object.unwrap().anchor {
        DrawingAnchor::TwoCell {
            from,
            to,
            edit_as,
        } => {
            assert_eq!(from.col, 4, "Absolute x must land in col 4");
            assert_eq!(from.row, 3, "Absolute y must land in row 3");
            assert_eq!(to.col, 6, "width extends from col 4 by 2");
            assert_eq!(to.row, 7, "height extends from row 3 by 4");
            assert_eq!(*edit_as, Some(EditAs::Absolute));
        }
        other => panic!("expected TwoCell with editAs=Absolute, got {other:?}"),
    }
}

#[test]
fn picture_anchor_within_cell_offsets_round_trip() {
    // Within-cell EMU offsets quantise to ClientAnchor 1024ths of the
    // column width (609,600 EMU) and 256ths of the row height
    // (190,500 EMU) using exact rational math. Use offsets that are
    // exact under that quantisation (multiples of 9,525 EMU for dx,
    // 47,625 EMU for dy) so the round-trip is exact.
    let from_col_off = 19_050i64; // 32/1024 of 609,600
    let from_row_off = 47_625i64; // 64/256 of 190,500
    let to_col_off = 295_275i64; // 496/1024 of 609,600
    let to_row_off = 142_875i64; // 192/256 of 190,500

    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_drawing(test_image("Picture 1", 1, 2).with_anchor(DrawingAnchor::TwoCell {
        from: CellMarker {
            col: 1,
            col_offset_emu: from_col_off,
            row: 2,
            row_offset_emu: from_row_off,
        },
        to: CellMarker {
            col: 4,
            col_offset_emu: to_col_off,
            row: 7,
            row_offset_emu: to_row_off,
        },
        edit_as: None,
    })).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    assert_eq!(images.len(), 1);
    if let DrawingAnchor::TwoCell { from, to, .. } = &images[0].object.unwrap().anchor {
        assert_eq!(from.col_offset_emu, from_col_off);
        assert_eq!(from.row_offset_emu, from_row_off);
        assert_eq!(to.col_offset_emu, to_col_off);
        assert_eq!(to.row_offset_emu, to_row_off);
    } else {
        panic!("expected TwoCell anchor");
    }

    // Synthesised width/height should reflect the cell span at
    // Excel's default cell sizes plus the within-cell delta.
    let img = images[0].payload;
    assert!(img.width_emu > 0, "width_emu should be synthesised non-zero");
    assert!(
        img.height_emu > 0,
        "height_emu should be synthesised non-zero"
    );

    // Span: 4-1=3 cols × 609,600 + (to_off - from_off).
    let expected_width = 3 * 609_600 + (to_col_off - from_col_off);
    let expected_height = 5 * 190_500 + (to_row_off - from_row_off);
    assert_eq!(img.width_emu, expected_width);
    assert_eq!(img.height_emu, expected_height);
}

#[test]
fn picture_anchor_over_hidden_rows_and_columns_survives() {
    // Hidden rows/columns render at zero extent, so their quantised
    // within-cell fractions degenerate to 0. The anchor's cells must
    // survive the round-trip and stay ordered (to >= from) even when
    // both endpoints touch zero-extent cells.
    let custom = DrawingAnchor::TwoCell {
        from: CellMarker {
            col: 2,
            col_offset_emu: 0,
            row: 3,
            row_offset_emu: 0,
        },
        to: CellMarker {
            col: 5,
            col_offset_emu: 0,
            row: 8,
            row_offset_emu: 0,
        },
        edit_as: None,
    };
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    for col in 2..=3 {
        ws.set_column_hidden(col, true);
    }
    for row in 3..=5 {
        ws.set_row_hidden(row, true);
    }
    ws.add_drawing(test_image("Picture 1", 0, 0).with_anchor(custom.clone())).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    assert_eq!(images.len(), 1);
    let DrawingAnchor::TwoCell { from, to, .. } = &images[0].object.unwrap().anchor else {
        panic!("expected TwoCell anchor");
    };
    assert_eq!(images[0].object.unwrap().anchor, custom, "anchor survives verbatim");
    assert!(
        (to.col, to.col_offset_emu) >= (from.col, from.col_offset_emu),
        "column endpoints stay ordered"
    );
    assert!(
        (to.row, to.row_offset_emu) >= (from.row, from.row_offset_emu),
        "row endpoints stay ordered"
    );
}

#[test]
fn negative_anchor_offsets_clamp_to_zero() {
    // MS-XLS ClientAnchor fractions are 0..=1024 (dx) and 0..=256
    // (dy); a negative within-cell offset must clamp to 0 on the
    // wire, not emit an out-of-range negative fraction.
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_drawing(test_image("Picture 1", 1, 2).with_anchor(DrawingAnchor::TwoCell {
        from: CellMarker {
            col: 1,
            col_offset_emu: -9_525,
            row: 2,
            row_offset_emu: -47_625,
        },
        to: CellMarker {
            col: 4,
            col_offset_emu: 0,
            row: 7,
            row_offset_emu: 0,
        },
        edit_as: None,
    })).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    let DrawingAnchor::TwoCell { from, .. } = &images[0].object.unwrap().anchor else {
        panic!("expected TwoCell anchor");
    };
    assert_eq!(
        (from.col, from.col_offset_emu),
        (1, 0),
        "negative dx clamps to fraction 0"
    );
    assert_eq!(
        (from.row, from.row_offset_emu),
        (2, 0),
        "negative dy clamps to fraction 0"
    );
}

/// 58-byte 1x1 24-bit BMP (white pixel). Has the standard 14-byte
/// BITMAPFILEHEADER + 40-byte BITMAPINFOHEADER + 4-byte pixel row.
const TEST_BMP_1X1: &[u8] = &[
    0x42, 0x4D, 0x3A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x36, 0x00, 0x00, 0x00, 0x28, 0x00,
    0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x18, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x13, 0x0B, 0x00, 0x00, 0x13, 0x0B, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0x00,
];

#[test]
fn single_bmp_picture_round_trips() {
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.set_cell_value("A1", "anchor").expect("A1");
    ws.add_drawing(test_image_with_format(
        "BmpPic",
        1,
        2,
        ImageFormat::Bmp,
        TEST_BMP_1X1,
    )).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    assert_eq!(images.len(), 1);
    let img = images[0].payload;
    assert_eq!(img.format, ImageFormat::Bmp, "format must stay BMP");
    // Writer strips the 14-byte BITMAPFILEHEADER; reader synthesises
    // a fresh one. The synthesised header has different bfSize and
    // bfOffBits (computed) but the body (DIB info+palette+pixels) is
    // identical.
    assert_eq!(&img.data[..2], b"BM", "BMP signature must survive");
    assert_eq!(
        &img.data[14..],
        &TEST_BMP_1X1[14..],
        "DIB body (info header + palette + pixels) must round-trip verbatim"
    );
}

/// **NOT a valid EMF file** — a deterministic byte pattern used to
/// exercise the BLIP wrapper round-trip. Tests below verify only
/// that the `OfficeArtBlipEMF` / `OfficeArtBlipWMF` framing + 34-byte
/// metafileHeader correctly survive write → read; the actual
/// metafile data is opaque to the writer and reader. Real EMF/WMF
/// parity against Excel is not tested because (a) Excel re-renders
/// metafiles as PNG on SaveAs anyway, (b) generating a valid EMF
/// in pure Rust is non-trivial.
const TEST_EMF_BYTES: &[u8] = &[
    0x01, 0x00, 0x00, 0x00, 0x68, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x80, 0x07, 0x00, 0x00, 0x38, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0xF0, 0x1A, 0x00, 0x00, 0xA0, 0x0F, 0x00, 0x00, 0x20, 0x45, 0x4D, 0x46, 0x00, 0x00, 0x01, 0x00,
    0x6C, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x80, 0x07, 0x00, 0x00, 0x38, 0x04, 0x00, 0x00, 0x20, 0x03, 0x00, 0x00, 0xE0, 0x01, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xCC, 0x4F, 0x00, 0x00, 0x60, 0x37, 0x00, 0x00,
    0x0E, 0x00, 0x00, 0x00, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00,
    0x14, 0x00, 0x00, 0x00,
];

/// Synthetic 1x1 TIFF (little-endian, 8-bit grayscale). 110 bytes,
/// generated to be a structurally valid TIFF.
const TEST_TIFF_BYTES: &[u8] = &[
    0x49, 0x49, 0x2A, 0x00, 0x08, 0x00, 0x00, 0x00, 0x07, 0x00, // header + IFD offset + entry count
    // IFD entries (each 12 bytes):
    0x00, 0x01, 0x03, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, // ImageWidth=1
    0x01, 0x01, 0x03, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, // ImageLength=1
    0x02, 0x01, 0x03, 0x00, 0x01, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, // BitsPerSample=8
    0x03, 0x01, 0x03, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, // Compression=1
    0x06, 0x01, 0x03, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, // PhotometricInterp=1
    0x11, 0x01, 0x04, 0x00, 0x01, 0x00, 0x00, 0x00, 0x6A, 0x00, 0x00, 0x00, // StripOffsets=106
    0x17, 0x01, 0x04, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, // StripByteCounts=1
    0x00, 0x00, 0x00, 0x00, // next IFD = none
    0xFF, // pixel data (1 byte)
];

/// Minimal 35-byte 1x1 GIF87a (transparent).
const TEST_GIF_BYTES: &[u8] = &[
    0x47, 0x49, 0x46, 0x38, 0x37, 0x61, // "GIF87a"
    0x01, 0x00, 0x01, 0x00, // width=1, height=1
    0x80, 0x00, 0x00, // GCT flag, bg index, aspect
    0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, // 2-entry GCT
    0x2C, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, // image descriptor
    0x02, 0x02, 0x44, 0x01, 0x00, // LZW data
    0x3B, // trailer
];

/// **In-process only**: a 110-byte hand-crafted TIFF byte pattern.
/// The test below exercises the `OfficeArtBlipTIFF` framing (same
/// raster layout as PNG/JPEG, no metafileHeader) but no Excel
/// parity test is included. Excel typically converts TIFF input to
/// PNG on SaveAs, so the format tag does not survive an Excel
/// round-trip — only in-process is meaningful.
#[test]
fn tiff_blip_wrapper_round_trips_in_process() {
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_drawing(test_image_with_format(
        "TiffPic",
        1,
        1,
        ImageFormat::Tiff,
        TEST_TIFF_BYTES,
    )).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    assert_eq!(images.len(), 1, "TIFF must round-trip");
    let img = images[0].payload;
    assert_eq!(img.format, ImageFormat::Tiff, "format must stay TIFF");
    assert_eq!(
        img.data, TEST_TIFF_BYTES,
        "TIFF bytes must round-trip verbatim"
    );
}

#[test]
fn gif_input_is_routed_through_png_blip_and_format_tag_flips() {
    // **Documented limitation.** GIF has no native Office binary
    // blip variant (MS-ODRAW's msoblip* enum skips GIF entirely).
    // The writer routes GIF input through the PNG blip path so the
    // bytes survive in-process round-trip, but the format tag
    // flips from Gif to Png on read because the reader sees a
    // BLIP_PNG header.
    //
    // No Excel parity test for GIF — Excel converts GIF to PNG on
    // insert anyway, so the format tag flips through Excel too.
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_drawing(test_image_with_format(
        "GifPic",
        1,
        1,
        ImageFormat::Gif,
        TEST_GIF_BYTES,
    )).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    assert_eq!(images.len(), 1, "GIF input must produce one round-tripped image");
    let img = images[0].payload;
    assert_eq!(
        img.format,
        ImageFormat::Png,
        "GIF input flips to Png because it's emitted through the PNG blip path"
    );
    assert_eq!(
        img.data, TEST_GIF_BYTES,
        "GIF bytes survive verbatim even though the format tag flips"
    );
}

#[test]
fn emf_blip_wrapper_round_trips_opaque_bytes_in_process() {
    // Verifies the OfficeArtBlipEMF framing: header + UID + 34-byte
    // metafileHeader + opaque payload survive writer → reader with
    // exact byte equality. The payload is NOT a valid EMF file —
    // this test is honestly named to disclose that it exercises the
    // blip wrapper, not full EMF support.
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_drawing(test_image_with_format(
        "EmfPic",
        1,
        1,
        ImageFormat::Emf,
        TEST_EMF_BYTES,
    )).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    assert_eq!(images.len(), 1, "EMF blip must round-trip");
    let img = images[0].payload;
    assert_eq!(img.format, ImageFormat::Emf, "format must stay EMF");
    assert_eq!(
        img.data, TEST_EMF_BYTES,
        "Payload bytes must round-trip verbatim through the metafileHeader"
    );
}

#[test]
fn wmf_blip_wrapper_round_trips_opaque_bytes_in_process() {
    // Same as the EMF test but for the WMF blip variant. Uses the
    // same opaque synthetic payload — WMF and EMF share the 34-byte
    // metafileHeader layout. Honestly disclosed as a blip-wrapper
    // test, not a full WMF round-trip.
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_drawing(test_image_with_format(
        "WmfPic",
        1,
        1,
        ImageFormat::Wmf,
        TEST_EMF_BYTES,
    )).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    assert_eq!(images.len(), 1, "WMF blip must round-trip");
    let img = images[0].payload;
    assert_eq!(img.format, ImageFormat::Wmf, "format must stay WMF");
    assert_eq!(
        img.data, TEST_EMF_BYTES,
        "Payload bytes must round-trip verbatim"
    );
}

#[test]
fn png_and_bmp_coexist_on_one_sheet() {
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_drawing(test_image("PngPic", 0, 0)).unwrap();
    ws.add_drawing(test_image_with_format(
        "BmpPic",
        5,
        5,
        ImageFormat::Bmp,
        TEST_BMP_1X1,
    )).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    assert_eq!(images.len(), 2);
    assert_eq!(images[0].payload.format, ImageFormat::Png);
    assert_eq!(images[1].payload.format, ImageFormat::Bmp);
}

#[test]
fn single_jpeg_picture_round_trips() {
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.set_cell_value("A1", "anchor").expect("A1");
    ws.add_drawing(test_image_with_format(
        "JpegPic",
        1,
        2,
        ImageFormat::Jpeg,
        TEST_JPEG_1X1,
    )).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    assert_eq!(images.len(), 1, "JPEG must round-trip");
    let img = images[0].payload;
    assert_eq!(img.format, ImageFormat::Jpeg, "format must stay JPEG");
    assert_eq!(
        img.data, TEST_JPEG_1X1,
        "JPEG bytes must round-trip verbatim"
    );
}

#[test]
fn png_and_jpeg_coexist_on_one_sheet() {
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_drawing(test_image("PngPic", 0, 0)).unwrap();
    ws.add_drawing(test_image_with_format(
        "JpegPic",
        5,
        5,
        ImageFormat::Jpeg,
        TEST_JPEG_1X1,
    )).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    assert_eq!(images.len(), 2);
    // Map by format since reader order should match writer order.
    assert_eq!(images[0].payload.format, ImageFormat::Png);
    assert_eq!(images[0].payload.data, TEST_PNG_1X1);
    assert_eq!(images[1].payload.format, ImageFormat::Jpeg);
    assert_eq!(images[1].payload.data, TEST_JPEG_1X1);
}

#[test]
fn multiple_pictures_round_trip_on_one_sheet() {
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_drawing(test_image("Picture 1", 0, 0)).unwrap();
    ws.add_drawing(test_image("Picture 2", 4, 4)).unwrap();
    ws.add_drawing(test_image("Picture 3", 8, 8)).unwrap();

    let parsed = write_then_read(&wb);
    let images = images_of(parsed.worksheet(0).unwrap());
    assert_eq!(images.len(), 3, "all three pictures must round-trip");
    for img in images {
        assert_eq!(img.payload.format, ImageFormat::Png);
        assert_eq!(
            img.payload.data, TEST_PNG_1X1,
            "each picture's PNG bytes must survive verbatim"
        );
    }
}

#[test]
fn picture_and_comment_coexist_on_same_sheet() {
    use duke_sheets_core::CellComment;

    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_drawing(test_image("Picture 1", 1, 1)).unwrap();
    ws.set_comment_at(3, 3, CellComment::new("Alice", "A note"))
        .expect("set comment");

    let parsed = write_then_read(&wb);
    let ws_in = parsed.worksheet(0).unwrap();
    assert_eq!(ws_in.image_count(), 1, "picture must survive");
    assert_eq!(ws_in.comment_count(), 1, "comment must survive");
    assert_eq!(ws_in.comment_at(3, 3).unwrap().plain_text(), "A note");
    assert_eq!(
        images_of(ws_in)[0].object.unwrap().meta.name.as_deref(),
        Some("Picture 1")
    );
}

#[test]
fn pictures_on_multiple_sheets_round_trip() {
    let mut wb = Workbook::new();
    wb.rename_worksheet(0, "First").expect("rename");
    wb.add_worksheet_with_name("Second").expect("add");

    wb.worksheet_mut(0)
        .unwrap()
        .add_drawing(test_image("Pic on First", 0, 0)).unwrap();
    wb.worksheet_mut(1)
        .unwrap()
        .add_drawing(test_image("Pic on Second", 2, 2)).unwrap();

    let parsed = write_then_read(&wb);
    assert_eq!(parsed.worksheet(0).unwrap().image_count(), 1);
    assert_eq!(parsed.worksheet(1).unwrap().image_count(), 1);
    assert_eq!(
        images_of(parsed.worksheet(0).unwrap())[0]
            .meta
            .name
            .as_deref(),
        Some("Pic on First")
    );
    assert_eq!(
        images_of(parsed.worksheet(1).unwrap())[0]
            .meta
            .name
            .as_deref(),
        Some("Pic on Second")
    );
}

/// LibreOffice envelope check: write an XLS with one PNG image,
/// push to the LO shared dir, open via URP, read the anchor cell's
/// value back. Catches structural malformations in the Escher tree
/// (Blip/FBSE/BSTORE_CONTAINER + picture SP_CONTAINER) that would
/// make LO refuse the file.
#[test]
fn lo_can_open_xls_with_picture_we_emit() {
    duke_sheets_test_harness::lo::ensure_lo();

    const SHARED_DIR: &str = "/tmp/duke-sheets-urp";

    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.set_cell_value("A1", 42.0).expect("A1");
    ws.add_drawing(test_image("Picture 1", 2, 3)).unwrap();
    // A second image past the 8224-byte record cap, so the
    // MSODRAWINGGROUP → CONTINUE split is validated by a real
    // consumer's loader, not just our own reader.
    let big_data = {
        let mut d = TEST_PNG_1X1.to_vec();
        d.resize(20_000, 0xAB);
        d
    };
    ws.add_drawing(test_image_with_format(
        "Picture 2",
        6,
        3,
        ImageFormat::Png,
        &big_data,
    )).unwrap();

    let bytes = XlsWriter::write_to_bytes(&wb).expect("serialize");
    std::fs::create_dir_all(SHARED_DIR).expect("shared dir");
    let pid = std::process::id();
    let path = format!("{SHARED_DIR}/duke_picture_{pid}.xls");
    std::fs::write(&path, &bytes).expect("write");

    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap();
    let outcome: Result<f64, String> = rt.block_on(async {
        let mut bridge =
            duke_sheets_libreoffice::bridge::LibreOfficeBridge::connect("127.0.0.1", 2002)
                .await
                .map_err(|e| format!("connect: {e}"))?;
        let mut wb_in = bridge
            .open_workbook(&path)
            .await
            .map_err(|e| format!("open: {e}"))?;
        wb_in
            .get_cell_value("A1")
            .await
            .map_err(|e| format!("A1: {e}"))
    });
    let _ = std::fs::remove_file(&path);
    let a1 = outcome.expect("LO must open our XLS with picture without error");
    assert!(
        (a1 - 42.0).abs() < 1e-9,
        "A1 must round-trip; got {a1} (expected 42)"
    );
}

#[test]
fn empty_workbook_emits_no_blip_store() {
    // No images = no MSODRAWINGGROUP / MSODRAWING / BSTORE_CONTAINER
    // emission. Confirm by writing, parsing, and verifying the
    // workbook stream has zero drawing-group records.
    let mut wb = Workbook::new();
    wb.worksheet_mut(0)
        .unwrap()
        .set_cell_value("A1", "value")
        .expect("A1");

    let bytes = XlsWriter::write_to_bytes(&wb).expect("serialize");
    let parsed = XlsReader::read(Cursor::new(&bytes)).expect("read");
    assert_eq!(parsed.worksheet(0).unwrap().image_count(), 0);
}

#[test]
fn msodrawinggroup_split_across_multiple_records_round_trips() {
    // Excel splits a large OfficeArt drawing group across multiple
    // MSODRAWINGGROUP records (not CONTINUE records), each carrying a
    // fragment of one logical DggContainer byte stream. The reader must
    // concatenate every MSODRAWINGGROUP body before walking the Escher
    // tree, or blips after the first split point are lost.
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.set_cell_value("A1", "anchor").expect("A1");
    ws.add_drawing(test_image("First", 1, 1)).unwrap();
    ws.add_drawing(test_image("Second", 6, 10)).unwrap();

    let bytes = XlsWriter::write_to_bytes(&wb).expect("serialize");

    // Extract the Workbook stream and split the single MSODRAWINGGROUP
    // record body into two MSODRAWINGGROUP records mid-container.
    let cfb = duke_sheets_xls::cfb::CompoundFile::open(Cursor::new(&bytes)).expect("open cfb");
    let stream = cfb.read_stream("/Workbook").expect("workbook stream");

    const MSODRAWINGGROUP: u16 = 0x00EB;
    let mut rebuilt = Vec::with_capacity(stream.len() + 4);
    let mut cursor = 0usize;
    let mut split = false;
    while cursor + 4 <= stream.len() {
        let id = u16::from_le_bytes([stream[cursor], stream[cursor + 1]]);
        let len = u16::from_le_bytes([stream[cursor + 2], stream[cursor + 3]]) as usize;
        let body = &stream[cursor + 4..cursor + 4 + len];
        if id == MSODRAWINGGROUP && !split {
            split = true;
            let mid = len / 2;
            for part in [&body[..mid], &body[mid..]] {
                rebuilt.extend_from_slice(&MSODRAWINGGROUP.to_le_bytes());
                rebuilt.extend_from_slice(&(part.len() as u16).to_le_bytes());
                rebuilt.extend_from_slice(part);
            }
        } else {
            rebuilt.extend_from_slice(&stream[cursor..cursor + 4 + len]);
        }
        cursor += 4 + len;
    }
    assert!(split, "expected a MSODRAWINGGROUP record in the stream");

    let mut builder = duke_sheets_xls::cfb::CompoundFileBuilder::new();
    builder.add_stream("/Workbook", rebuilt).expect("add stream");
    let patched = builder.build().expect("rebuild cfb");

    let parsed = XlsReader::read(Cursor::new(&patched)).expect("read back");
    let images = images_of(parsed.worksheet(0).unwrap());
    assert_eq!(
        images.len(),
        2,
        "both blips must survive a split MSODRAWINGGROUP"
    );
    assert_eq!(images[0].payload.data(), TEST_PNG_1X1);
    assert_eq!(images[1].payload.data(), TEST_PNG_1X1);
}
