//! End-to-end tests for password-protected XLSX (OOXML).
//!
//! Two fixtures cover both modern OOXML encryption variants:
//!
//! - `agile_aes256.xlsx` — generated by LibreOffice's `storeToURL`.
//!   Despite the filename, this is actually **Standard Encryption**
//!   (vMajor=3, vMinor=2, AES-CBC + SHA-1 KDF, 50k iterations) — LO's
//!   default for password-protected `.xlsx`.
//!
//! - `xlsx_agile_excel.xlsx` — generated by real Excel via the COM
//!   bridge. This is **Agile Encryption** (vMajor=4, vMinor=4, AES-256
//!   + SHA-512 KDF, 100k iterations) — Office 2010+'s default.
//!
//! Both fixtures encode the same content: A1 = "hello crypto", B1 = 42.0.
//! Generate with:
//!   - LO/Standard: `mise run crypto:fixtures`
//!   - Excel/Agile: `mise run crypto:fixtures:excel` (requires VM up)

use std::path::PathBuf;

use duke_sheets_xlsx::{XlsxError, XlsxReadOptions, XlsxReader};

fn fixture(name: &str) -> Option<PathBuf> {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("..");
    p.push("duke-sheets-crypto");
    p.push("tests/fixtures");
    p.push(name);
    p.canonicalize().ok()
}

const FIXTURE_PASSWORD: &str = "duke-test-pw";

fn skip_if_missing(name: &str) -> Option<PathBuf> {
    let Some(p) = fixture(name) else {
        eprintln!("SKIP: {name} not present; run `mise run crypto:fixtures`");
        return None;
    };
    Some(p)
}

fn assert_decrypted_workbook(workbook: &duke_sheets_core::workbook::Workbook) {
    let sheet = workbook.worksheet(0).expect("sheet 0");
    let a1 = sheet.get_value("A1").expect("A1 must exist");
    let b1 = sheet.get_value("B1").expect("B1 must exist");
    assert_eq!(a1.as_string().as_deref(), Some("hello crypto"), "A1 value");
    assert_eq!(b1.as_number(), Some(42.0), "B1 value");
}

#[test]
fn agile_xlsx_fails_without_password() {
    let Some(path) = skip_if_missing("agile_aes256.xlsx") else {
        return;
    };
    let bytes = std::fs::read(&path).expect("read fixture");
    let err = XlsxReader::read_bytes_with(&bytes, &XlsxReadOptions::default())
        .expect_err("must require password");
    assert!(
        matches!(err, XlsxError::Encrypted(_)),
        "expected Encrypted, got {err:?}"
    );
}

#[test]
fn agile_xlsx_decrypts_with_correct_password() {
    let Some(path) = skip_if_missing("agile_aes256.xlsx") else {
        return;
    };
    let workbook = XlsxReader::read_file_with(&path, &XlsxReadOptions { password: Some(FIXTURE_PASSWORD.to_string()), ..Default::default() })
        .expect("decryption with correct password must succeed");
    assert_decrypted_workbook(&workbook);
}

#[test]
fn agile_xlsx_wrong_password_yields_bad_password() {
    let Some(path) = skip_if_missing("agile_aes256.xlsx") else {
        return;
    };
    let err = XlsxReader::read_file_with(&path, &XlsxReadOptions { password: Some("wrong-password".to_string()), ..Default::default() })
        .expect_err("must reject wrong password");
    assert!(
        matches!(err, XlsxError::BadPassword),
        "expected BadPassword, got {err:?}"
    );
}

#[test]
fn excel_agile_xlsx_fails_without_password() {
    let Some(path) = skip_if_missing("xlsx_agile_excel.xlsx") else {
        return;
    };
    let bytes = std::fs::read(&path).expect("read");
    let err = XlsxReader::read_bytes_with(&bytes, &XlsxReadOptions::default())
        .expect_err("must require password");
    assert!(
        matches!(err, XlsxError::Encrypted(_)),
        "expected Encrypted, got {err:?}"
    );
}

#[test]
fn excel_agile_xlsx_decrypts_with_correct_password() {
    let Some(path) = skip_if_missing("xlsx_agile_excel.xlsx") else {
        return;
    };
    let workbook = XlsxReader::read_file_with(&path, &XlsxReadOptions { password: Some(FIXTURE_PASSWORD.to_string()), ..Default::default() })
        .expect("Agile decryption with correct password must succeed");
    assert_decrypted_workbook(&workbook);
}

#[test]
fn excel_agile_xlsx_wrong_password_yields_bad_password() {
    let Some(path) = skip_if_missing("xlsx_agile_excel.xlsx") else {
        return;
    };
    let err = XlsxReader::read_file_with(&path, &XlsxReadOptions { password: Some("wrong-password".to_string()), ..Default::default() })
        .expect_err("must reject wrong password");
    assert!(
        matches!(err, XlsxError::BadPassword),
        "expected BadPassword, got {err:?}"
    );
}

#[test]
fn velvet_sweatshop_auto_decrypts_when_enabled() {
    let Some(path) = skip_if_missing("xlsx_velvet_sweatshop.xlsx") else {
        return;
    };
    let bytes = std::fs::read(&path).expect("read");
    let workbook = XlsxReader::read_bytes_with(&bytes, &XlsxReadOptions { try_velvet_sweatshop: true, ..Default::default() })
        .expect("VelvetSweatshop sentinel must auto-decrypt");
    assert_decrypted_workbook(&workbook);
}

#[test]
fn velvet_sweatshop_disabled_yields_encrypted() {
    let Some(path) = skip_if_missing("xlsx_velvet_sweatshop.xlsx") else {
        return;
    };
    let bytes = std::fs::read(&path).expect("read");
    let err = XlsxReader::read_bytes_with(&bytes, &XlsxReadOptions::default())
        .expect_err("strict mode must error without a password");
    assert!(
        matches!(err, XlsxError::Encrypted(_)),
        "expected Encrypted, got {err:?}"
    );
}

#[test]
fn velvet_sweatshop_doesnt_swallow_real_password_files() {
    let Some(path) = skip_if_missing("xlsx_agile_excel.xlsx") else {
        return;
    };
    let bytes = std::fs::read(&path).expect("read");
    let err = XlsxReader::read_bytes_with(&bytes, &XlsxReadOptions { try_velvet_sweatshop: true, ..Default::default() })
        .expect_err("real password file must still error when sentinel doesn't match");
    assert!(
        matches!(err, XlsxError::Encrypted(_)),
        "expected Encrypted (not BadPassword), got {err:?}"
    );
}

#[test]
fn plain_xlsx_password_ignored() {
    let Some(path) = skip_if_missing("agile_aes256.plain.xlsx") else {
        return;
    };
    let workbook = XlsxReader::read_file_with(&path, &XlsxReadOptions { password: Some("anything".to_string()), ..Default::default() })
        .expect("plain XLSX should open regardless of password arg");
    assert!(workbook.sheet_count() >= 1);
}
